import type { EasterEggProfile } from "./types";

export const easterEggs: EasterEggProfile[] = [
  {
    id: "xipubawang",
    slug: "xipubawang",
    nameCn: "西普坝王",
    nameEn: "XPBW",
    title: "你触发了彩蛋人格：西普坝王",
    summary: "你把低门槛收益和稳定正反馈玩到了极致，经济节奏非常清晰。",
    revealLine: "哟，是坝中王来了",
    rarityLabel: "特殊彩蛋",
    threshold: 10,
    tone: "mint",
    signalWords: ["低门槛收益", "坝王经济", "稳定进账"],
    kind: "special",
    imageUrl: "/images/personas/xipubawang.webp",
  },
  {
    id: "duoshedelang",
    slug: "duoshedelang",
    nameCn: "夺舍的狼",
    nameEn: "SUXIN-G",
    title: "你触发了彩蛋人格：夺舍的狼",
    summary: "你在关键节点会切成极凶的收割模式，像突然换了一个人。",
    revealLine: "头甲枪背包胸挂花来！",
    rarityLabel: "特殊彩蛋",
    threshold: 10,
    tone: "signal",
    signalWords: ["残局收割", "反差爆发", "极限转换"],
    kind: "special",
    imageUrl: "/images/personas/duoshedelang.webp",
  },
  {
    id: "linshu",
    slug: "linshu",
    nameCn: "林树",
    nameEn: "BIGEA-R",
    title: "你触发了彩蛋人格：林树",
    summary: "你在高压地图和强对抗里保持推进，开口就打穿节奏。",
    revealLine: "威风的龙，到！",
    rarityLabel: "特殊彩蛋",
    threshold: 10,
    tone: "signal",
    signalWords: ["高压推进", "突击开口", "执行力"],
    kind: "special",
    imageUrl: "/images/personas/linshu.webp",
  },
  {
    id: "haotian",
    slug: "haotian",
    nameCn: "昊天",
    nameEn: "LUNA-K",
    title: "你触发了彩蛋人格：昊天",
    summary: "你更偏向信息驱动的高压推进，先看穿再压穿。",
    revealLine: "策划我求求你了",
    rarityLabel: "特殊彩蛋",
    threshold: 10,
    tone: "signal",
    signalWords: ["侦查推进", "高压读局", "节奏压制"],
    kind: "special",
    imageUrl: "/images/personas/haotian.webp",
  },
];

export const easterEggsById = Object.fromEntries(
  easterEggs.map((profile) => [profile.id, profile]),
) as Partial<Record<EasterEggProfile["id"], EasterEggProfile>>;
