import type { PartialPersonaScoreMap, QuestionId } from "./types";

// Generated from Desktop persona score workbook (Q1A..Q23X).
// Workbook row index follows questionBank declaration order in questions.ts.
export const personaSignalOverrides: Partial<Record<QuestionId, Record<string, PartialPersonaScoreMap>>> = {
  "gunfire": {
    "read-and-join": {
      menggonglang: 1,
      jiaoguan: 1,
      shushu: -1,
      tujiu: 1,
      weilong: 1,
      saiyide: -1,
      hadesen: 2,
      leisi: -1,
      demulan: 1,
      tangwang: -1,
      jiahao: 1,
      benzhigaoshou: 3,
      shoucangjia: -2,
    },
    "late-loot": {
      menggonglang: -1,
      shushu: -1,
      tujiu: 3,
      weilong: 1,
      saiyide: -1,
      hadesen: 3,
      leisi: -2,
      duya: 2,
      demulan: 1,
      tangwang: -1,
      laobeizha: 1,
      benzhigaoshou: 2,
      shoucangjia: -2,
    },
    "rush-now": {
      menggonglang: 3,
      laoban: -1,
      shushu: -3,
      tujiu: 1,
      weilong: 1,
      saiyide: 3,
      hadesen: -1,
      leisi: 3,
      duya: 1,
      jiahao: 3,
      benzhigaoshou: 1,
      shoucangjia: -3,
    },
    "call-the-team": {
      menggonglang: 1,
      laoban: 2,
      jiaoguan: 3,
      weilong: 4,
      saiyide: 2,
      hadesen: 1,
      demulan: 2,
      mama: 3,
      benzhigaoshou: 1,
    },
    "ignore-for-loot": {
      menggonglang: -2,
      laoban: 3,
      shushu: 3,
      tangwang: 3,
      jiahao: -2,
      shoucangjia: 3,
    },
  },
  "after-fight": {
    "leave-with-profit": {
      menggonglang: -1,
      shushu: 2,
      tujiu: 2,
      saiyide: -1,
      hadesen: 1,
      duya: 1,
      jiahao: -1,
      benzhigaoshou: 1,
      shoucangjia: 1,
    },
    "hold-angles": {
      menggonglang: 1,
      laoban: 1,
      jiaoguan: 1,
      shushu: -2,
      weilong: 1,
      saiyide: 1,
      hadesen: 2,
      demulan: 1,
      mama: 1,
      tangwang: -1,
      jiahao: 1,
      benzhigaoshou: 3,
      shoucangjia: -2,
    },
    "fight-next": {
      menggonglang: 3,
      jiaoguan: 1,
      shushu: -3,
      weilong: 1,
      saiyide: 2,
      leisi: 3,
      duya: 1,
      demulan: 1,
      tangwang: -3,
      jiahao: 2,
      benzhigaoshou: 1,
      shoucangjia: -3,
    },
    "stabilize-squad": {
      menggonglang: 1,
      laoban: 1,
      jiaoguan: 3,
      weilong: 2,
      saiyide: 1,
      hadesen: 1,
      demulan: 2,
      mama: 3,
      jiahao: 1,
      benzhigaoshou: 1,
    },
    "loot-two-more": {
      menggonglang: -1,
      laoban: 3,
      jiaoguan: -1,
      shushu: 3,
      tujiu: 2,
      weilong: -1,
      saiyide: -1,
      leisi: -1,
      duya: 2,
      demulan: -1,
      tangwang: 6,
      jiahao: -1,
      shoucangjia: 3,
    },
  },
  "loadout": {
    "budget-smart": {
      menggonglang: -2,
      laoban: 1,
      shushu: 3,
      tujiu: 1,
      saiyide: -1,
      hadesen: -1,
      leisi: -1,
      duya: 1,
      demulan: -2,
      tangwang: 2,
      jiahao: -2,
      benzhigaoshou: 1,
      shoucangjia: 2,
    },
    "full-send": {
      menggonglang: 9,
      shushu: -2,
      saiyide: 2,
      leisi: 2,
      demulan: 2,
      tangwang: -3,
      jiahao: 3,
      benzhigaoshou: 2,
    },
    "style-build": {
      menggonglang: 2,
      shushu: -3,
      tangwang: -3,
      jiahao: 9,
      benzhigaoshou: 1,
    },
    "torment-kit": {
      menggonglang: -1,
      laoban: 1,
      shushu: 3,
      tujiu: 3,
      tangwang: 2,
      laobeizha: 3,
      duqiaolai: 3,
      jiahao: -1,
      benzhigaoshou: 1,
    },
    "stable-kit": {
      menggonglang: 1,
      laoban: 1,
      jiaoguan: 1,
      shushu: 1,
      tujiu: 1,
      weilong: 1,
      hadesen: 2,
      demulan: -1,
      benzhigaoshou: 3,
    },
  },
  "backpack": {
    "ga-20": {
      laoban: -3,
      jiaoguan: 1,
      shushu: 2,
      tujiu: 1,
      weilong: 1,
      saiyide: 1,
      hadesen: 2,
      demulan: -1,
      benzhigaoshou: 3,
    },
    "take-from-bots": {
      menggonglang: -2,
      laoban: -3,
      shushu: 3,
      tujiu: 1,
      weilong: -1,
      hadesen: -1,
      duya: 1,
      demulan: -3,
      tangwang: 6,
      laobeizha: 1,
      duqiaolai: 1,
      jiahao: -1,
      shoucangjia: 2,
    },
    "green-15": {
      menggonglang: -1,
      laoban: -3,
      shushu: 4,
      tujiu: 1,
      hadesen: 1,
      leisi: -1,
      demulan: -1,
      tangwang: 3,
      laobeizha: 1,
      duqiaolai: 1,
      jiahao: -1,
      shoucangjia: 4,
    },
    "gold-30": {
      menggonglang: 3,
      laoban: 1,
      shushu: -3,
      saiyide: 1,
      hadesen: 2,
      leisi: 1,
      duya: 1,
      demulan: 2,
      tangwang: -3,
      jiahao: 3,
      benzhigaoshou: 2,
    },
    "red-45": {
      menggonglang: 1,
      laoban: 6,
      shushu: -4,
      hadesen: 1,
      leisi: 1,
      demulan: 2,
      jiahao: 1,
      benzhigaoshou: 1,
    },
  },
  "operator": {
    "assault": {
      menggonglang: 3,
      laoban: -3,
      jiaoguan: -1,
      shushu: -1,
      tujiu: 1,
      weilong: 3,
      saiyide: 3,
      leisi: 3,
      duya: 2,
      demulan: 1,
      mama: -3,
      tangwang: 1,
      laobeizha: -3,
      duqiaolai: -3,
      jiahao: 3,
      benzhigaoshou: 3,
    },
    "recon": {
      menggonglang: 3,
      laoban: -3,
      jiaoguan: -1,
      shushu: -1,
      tujiu: 3,
      weilong: 1,
      hadesen: 3,
      leisi: -1,
      duya: 2,
      demulan: 3,
      mama: 1,
      laobeizha: 3,
      duqiaolai: 3,
      jiahao: 3,
      benzhigaoshou: 3,
    },
    "support": {
      laoban: 6,
      jiaoguan: 2,
      shushu: 3,
      tujiu: 1,
      weilong: 1,
      leisi: -2,
      mama: 8,
      tangwang: 3,
    },
    "engineer": {
      jiaoguan: 6,
      weilong: 1,
      hadesen: 1,
      demulan: 1,
      mama: 1,
      duqiaolai: 3,
      benzhigaoshou: 2,
    },
    "saiyide": {
      menggonglang: 3,
      laoban: -2,
      jiaoguan: 1,
      weilong: 1,
      saiyide: 6,
      hadesen: 1,
      leisi: 3,
      duya: 2,
      demulan: 1,
      jiahao: 2,
      benzhigaoshou: 3,
    },
  },
  "map": {
    "dam": {
      menggonglang: 1,
      laoban: 1,
      shushu: 3,
      tujiu: 1,
      weilong: 1,
      saiyide: 3,
      hadesen: 2,
      leisi: 1,
      duya: 2,
      tangwang: 3,
      laobeizha: 1,
      duqiaolai: -3,
      jiahao: 1,
      benzhigaoshou: 1,
      shoucangjia: 3,
    },
    "valley": {
      shushu: 2,
      tujiu: 1,
      weilong: 1,
      hadesen: -1,
      leisi: 1,
      tangwang: 2,
      laobeizha: 3,
      duqiaolai: -3,
    },
    "bakash": {
      menggonglang: 3,
      laoban: 2,
      shushu: 1,
      tujiu: 3,
      weilong: 1,
      saiyide: 3,
      hadesen: 1,
      leisi: 3,
      duya: 1,
      tangwang: 1,
      laobeizha: 3,
      duqiaolai: 1,
      jiahao: 3,
      benzhigaoshou: 3,
      shoucangjia: 1,
    },
    "space-base": {
      menggonglang: 3,
      laoban: 4,
      shushu: 3,
      tujiu: 1,
      weilong: 1,
      saiyide: 1,
      hadesen: 3,
      leisi: 3,
      duya: -1,
      demulan: 3,
      tangwang: 2,
      duqiaolai: 3,
      jiahao: 3,
      benzhigaoshou: 3,
      shoucangjia: 3,
    },
    "prison": {
      menggonglang: 2,
      laoban: 2,
      shushu: 1,
      tujiu: 1,
      weilong: 1,
      hadesen: -1,
      leisi: 3,
      duya: 4,
      laobeizha: 1,
      duqiaolai: 1,
      jiahao: 2,
      benzhigaoshou: 3,
      shoucangjia: 2,
    },
  },
  "difficulty": {
    "normal": {
      menggonglang: -1,
      shushu: 1,
      tangwang: 1,
      jiahao: -1,
      benzhigaoshou: 1,
    },
    "confidential": {
      menggonglang: 2,
      laoban: 1,
      shushu: 3,
      tujiu: 1,
      saiyide: 1,
      tangwang: 2,
      duqiaolai: 1,
      jiahao: 2,
      benzhigaoshou: 2,
      shoucangjia: 1,
    },
    "classified": {
      menggonglang: 3,
      laoban: 3,
      shushu: 2,
      tujiu: 2,
      saiyide: 2,
      tangwang: 2,
      duqiaolai: 2,
      jiahao: 3,
      benzhigaoshou: 3,
      shoucangjia: 2,
    },
  },
  "single-extract-priority": {
    "me-first": {
      laoban: 3,
      jiaoguan: -1,
      shushu: 2,
      tujiu: 3,
      weilong: -1,
      saiyide: -1,
      hadesen: 1,
      leisi: 1,
      duya: 2,
      mama: -1,
      tangwang: 2,
      benzhigaoshou: 1,
      shoucangjia: 2,
    },
    "teammate-first": {
      menggonglang: 1,
      jiaoguan: 3,
      shushu: 1,
      weilong: 4,
      saiyide: 2,
      mama: 3,
      jiahao: 1,
    },
    "loot-carrier": {
      menggonglang: 1,
      shushu: 2,
      tujiu: 1,
      weilong: 1,
      saiyide: 1,
      hadesen: 1,
      demulan: 1,
      tangwang: 1,
      jiahao: 2,
      benzhigaoshou: 1,
      shoucangjia: 2,
    },
    "big-safe": {
      tujiu: 1,
      weilong: 1,
      hadesen: 3,
      demulan: 2,
      jiahao: 2,
      benzhigaoshou: 1,
    },
    "all-extract": {
      menggonglang: 1,
      jiaoguan: 3,
      weilong: 4,
      saiyide: 3,
      duya: 2,
      demulan: 3,
      mama: 2,
      jiahao: 1,
      benzhigaoshou: 1,
    },
  },
  "asset-level": {
    "under-10m": {
      shushu: 1,
    },
    "10m-50m": {
      menggonglang: 1,
      shushu: 1,
      jiahao: 1,
    },
    "50m-100m": {
      menggonglang: 2,
      laoban: 1,
      shushu: 1,
      jiahao: 2,
      benzhigaoshou: 1,
      shoucangjia: 1,
    },
    "100m-200m": {
      menggonglang: 1,
      laoban: 2,
      shushu: 2,
      jiahao: 1,
      benzhigaoshou: 2,
      shoucangjia: 2,
    },
    "over-200m": {
      menggonglang: 1,
      laoban: 3,
      shushu: 3,
      jiahao: 1,
      benzhigaoshou: 3,
      shoucangjia: 3,
    },
  },
  "fun-source": {
    "easy-loot": {
      laoban: 1,
      shushu: 3,
      tangwang: 2,
      shoucangjia: 2,
    },
    "conquer-headon": {
      menggonglang: 3,
      shushu: -1,
      weilong: 0,
      saiyide: 2,
      leisi: 3,
      tangwang: -1,
      benzhigaoshou: 2,
    },
    "read-the-game": {
      menggonglang: 1,
      jiaoguan: 2,
      tujiu: 2,
      weilong: 2,
      saiyide: 3,
      hadesen: 2,
      leisi: 1,
      duya: 3,
      demulan: 2,
      mama: 1,
      laobeizha: 1,
      duqiaolai: 1,
      jiahao: 1,
      benzhigaoshou: 3,
    },
    "friends-extract": {
      menggonglang: 2,
      laoban: 3,
      jiaoguan: 2,
      shushu: 1,
      weilong: 2,
      saiyide: 2,
      hadesen: 1,
      leisi: 2,
      mama: 3,
      tangwang: 2,
      laobeizha: 1,
      duqiaolai: 2,
      jiahao: 2,
      benzhigaoshou: 1,
      shoucangjia: 1,
    },
    "fill-collection": {
      menggonglang: 1,
      laoban: 3,
      shushu: 3,
      leisi: 3,
      tangwang: 3,
      laobeizha: 1,
      duqiaolai: 1,
      jiahao: 1,
      shoucangjia: 8,
    },
    "tilt-people": {
      laobeizha: 6,
      duqiaolai: 2,
    },
    "camp-and-tax": {
      laobeizha: 2,
      duqiaolai: 6,
    },
  },
  "core-zone-quiet": {
    "cheap-and-earn": {
      laoban: 1,
      shushu: 3,
      tujiu: 1,
      tangwang: 4,
      benzhigaoshou: 1,
      shoucangjia: 3,
    },
    "collect-info": {
      menggonglang: 1,
      jiaoguan: 2,
      shushu: 1,
      tujiu: 2,
      weilong: 2,
      saiyide: 1,
      hadesen: 3,
      demulan: 2,
      mama: 3,
      jiahao: 1,
      benzhigaoshou: 3,
      shoucangjia: 1,
    },
    "occupy-and-fight": {
      menggonglang: 3,
      jiaoguan: 1,
      shushu: -2,
      weilong: 1,
      saiyide: 3,
      leisi: 4,
      duya: 2,
      demulan: 2,
      tangwang: -1,
      jiahao: 3,
    },
    "detour": {
      menggonglang: -1,
      jiaoguan: 1,
      shushu: 2,
      tujiu: -1,
      weilong: 1,
      hadesen: 1,
      leisi: -2,
      duya: -1,
      mama: 3,
      jiahao: -1,
      benzhigaoshou: 2,
    },
    "magnet-bomb": {
      menggonglang: 1,
      jiaoguan: -2,
      shushu: 1,
      tujiu: -1,
      weilong: -2,
      leisi: 4,
      duya: 3,
      mama: -2,
      tangwang: 4,
      laobeizha: 1,
      duqiaolai: 1,
      jiahao: 2,
      benzhigaoshou: -2,
    },
  },
  "teammate-downed": {
    "method-rescue": {
      menggonglang: 1,
      laoban: 1,
      jiaoguan: 2,
      weilong: 1,
      saiyide: 1,
      hadesen: 3,
      leisi: -1,
      demulan: 2,
      mama: 1,
      jiahao: 1,
      benzhigaoshou: 3,
    },
    "wipe-then-rescue": {
      menggonglang: 3,
      shushu: -1,
      weilong: 2,
      saiyide: 6,
      hadesen: 1,
      leisi: 3,
      duya: 2,
      demulan: 1,
      tangwang: 2,
      jiahao: 3,
      benzhigaoshou: 1,
    },
    "rescue-first": {
      menggonglang: 1,
      laoban: 3,
      jiaoguan: 2,
      weilong: 1,
      saiyide: 2,
      hadesen: -1,
      demulan: 1,
      mama: 3,
      tangwang: 2,
      jiahao: 1,
    },
    "cover-and-rescue": {
      menggonglang: 1,
      jiaoguan: 2,
      weilong: 4,
      saiyide: 1,
      demulan: 1,
      mama: 1,
      jiahao: 1,
      benzhigaoshou: 2,
    },
    "cut-losses": {
      menggonglang: -1,
      laoban: 1,
      jiaoguan: 1,
      shushu: 2,
      tujiu: 1,
      weilong: -2,
      saiyide: -2,
      hadesen: 2,
      leisi: 2,
      duya: 1,
      demulan: 1,
      mama: -1,
      tangwang: 1,
      jiahao: -1,
      benzhigaoshou: 1,
    },
  },
  "full-gear-shattered": {
    "revenge-now": {
      menggonglang: 3,
      laoban: 2,
      tujiu: 1,
      weilong: 2,
      saiyide: 4,
      leisi: 5,
      duya: 2,
      demulan: 2,
      laobeizha: 2,
      jiahao: 3,
    },
    "fallback-first": {
      menggonglang: 1,
      laoban: 2,
      jiaoguan: 1,
      shushu: 1,
      tujiu: 2,
      weilong: 2,
      saiyide: 1,
      hadesen: 2,
      leisi: 1,
      duya: 1,
      demulan: 2,
      mama: 3,
      tangwang: 2,
      jiahao: 1,
      benzhigaoshou: 2,
    },
    "recover-and-counter": {
      menggonglang: 2,
      jiaoguan: 3,
      tujiu: 2,
      weilong: 2,
      saiyide: 3,
      hadesen: 3,
      leisi: 2,
      duya: 2,
      demulan: 3,
      mama: 2,
      jiahao: 2,
      benzhigaoshou: 3,
    },
    "join-the-chaos": {
      saiyide: 9,
      leisi: 2,
      duya: 8,
      mama: 1,
      tangwang: 1,
      laobeizha: 8,
    },
    "no-armor": {
      menggonglang: -1,
      laoban: 1,
      shushu: 3,
      tangwang: 6,
      jiahao: -1,
      shoucangjia: 2,
    },
  },
  "red-loot-footsteps": {
    "freeze-hide": {
      laoban: 3,
      shushu: 3,
      tujiu: 2,
      weilong: 1,
      hadesen: 1,
      leisi: 1,
      duya: 2,
      mama: 2,
      tangwang: 3,
      benzhigaoshou: 1,
      shoucangjia: 3,
    },
    "pick-and-disrupt": {
      menggonglang: 2,
      jiaoguan: 1,
      tujiu: 2,
      weilong: 1,
      saiyide: 4,
      hadesen: 2,
      leisi: 2,
      duya: 4,
      demulan: 3,
      jiahao: 3,
      benzhigaoshou: 3,
    },
    "call-support": {
      menggonglang: 1,
      laoban: 3,
      jiaoguan: 3,
      shushu: 1,
      tujiu: 1,
      weilong: 2,
      saiyide: 2,
      hadesen: 3,
      leisi: 1,
      duya: 2,
      demulan: 2,
      mama: 3,
      tangwang: 1,
      jiahao: 1,
      benzhigaoshou: 2,
      shoucangjia: 1,
    },
    "route-out": {
      laoban: 2,
      jiaoguan: 1,
      shushu: 2,
      tujiu: 1,
      weilong: 1,
      saiyide: 1,
      hadesen: 4,
      leisi: 1,
      duya: 1,
      demulan: 1,
      mama: 1,
      tangwang: 2,
      benzhigaoshou: 1,
      shoucangjia: 4,
    },
    "keep-looting": {
      laoban: 2,
      shushu: 2,
      duya: 3,
      tangwang: 6,
      shoucangjia: 3,
    },
  },
  "last-gate-ambush": {
    "drop-and-detour": {
      menggonglang: -1,
      laoban: 3,
      jiaoguan: 1,
      shushu: 3,
      tujiu: 2,
      weilong: 1,
      saiyide: 1,
      hadesen: 2,
      leisi: -1,
      demulan: 1,
      mama: 3,
      tangwang: 3,
      jiahao: -1,
      benzhigaoshou: 2,
      shoucangjia: 3,
    },
    "info-then-go": {
      menggonglang: 1,
      jiaoguan: 3,
      shushu: 1,
      tujiu: 2,
      weilong: 2,
      saiyide: 2,
      hadesen: 3,
      leisi: 1,
      duya: 1,
      demulan: 2,
      mama: 3,
      tangwang: 1,
      jiahao: 1,
      benzhigaoshou: 3,
    },
    "fight-for-face": {
      menggonglang: 3,
      jiaoguan: 1,
      weilong: 2,
      saiyide: 5,
      hadesen: 1,
      leisi: 4,
      duya: 3,
      demulan: 2,
      jiahao: 2,
      benzhigaoshou: 1,
    },
    "vanguard-extract": {
      menggonglang: 2,
      jiaoguan: 3,
      weilong: 6,
      saiyide: 3,
      leisi: 3,
      duya: 2,
      demulan: 1,
      mama: 2,
      jiahao: 3,
      benzhigaoshou: 1,
    },
    "i-am-ambush": {
      menggonglang: -1,
      shushu: 1,
      tujiu: 3,
      hadesen: 1,
      duya: 4,
      tangwang: 1,
      laobeizha: 3,
      duqiaolai: 3,
      jiahao: 1,
      benzhigaoshou: 2,
    },
  },
  "team-split": {
    "try-comm-then-self-save": {
      menggonglang: 1,
      jiaoguan: 1,
      tujiu: 2,
      weilong: 1,
      hadesen: 3,
      duya: 1,
      demulan: 3,
      mama: 2,
      tangwang: 1,
      jiahao: 1,
      benzhigaoshou: 3,
    },
    "follow-me": {
      menggonglang: 3,
      jiaoguan: 2,
      weilong: 2,
      saiyide: 3,
      leisi: 4,
      duya: 2,
      demulan: 2,
      tangwang: 1,
      jiahao: 6,
      benzhigaoshou: 1,
    },
    "just-loot": {
      menggonglang: 1,
      shushu: 3,
      tujiu: 1,
      hadesen: 2,
      leisi: 2,
      duya: 2,
      demulan: 1,
      mama: 2,
      tangwang: 3,
      jiahao: 1,
      benzhigaoshou: 1,
      shoucangjia: 4,
    },
    "follow-one": {
      menggonglang: 1,
      laoban: 2,
      jiaoguan: 2,
      shushu: 2,
      weilong: 1,
      hadesen: 1,
      duya: 2,
      mama: 2,
      tangwang: 3,
      benzhigaoshou: 1,
      shoucangjia: 1,
    },
    "solo-rush": {
      menggonglang: 4,
      tujiu: 1,
      weilong: 0,
      saiyide: 4,
      leisi: 3,
      duya: 2,
      jiahao: 4,
      benzhigaoshou: 2,
    },
  },
  "hate-point": {
    "no-extract-after-wins": {
      menggonglang: 3,
      laoban: 2,
      jiaoguan: 1,
      tujiu: 2,
      weilong: 2,
      saiyide: 3,
      hadesen: 3,
      leisi: 4,
      duya: 2,
      demulan: 1,
      mama: 2,
      jiahao: 3,
      benzhigaoshou: 2,
    },
    "bad-comms": {
      menggonglang: 2,
      laoban: 1,
      jiaoguan: 3,
      weilong: 2,
      saiyide: 2,
      hadesen: 1,
      leisi: 1,
      duya: 1,
      demulan: 2,
      mama: 3,
      jiahao: 2,
      benzhigaoshou: 1,
    },
    "my-own-mistake": {
      menggonglang: 1,
      jiaoguan: 2,
      tujiu: 1,
      weilong: 2,
      saiyide: 2,
      hadesen: 1,
      leisi: 1,
      duya: 1,
      demulan: 3,
      mama: 1,
      jiahao: 3,
      benzhigaoshou: 4,
    },
    "dirty-enemy": {
      menggonglang: 3,
      jiaoguan: 1,
      tujiu: 1,
      weilong: 2,
      saiyide: 3,
      hadesen: 2,
      leisi: 4,
      duya: 2,
      demulan: 1,
      mama: 1,
      jiahao: 3,
      benzhigaoshou: 1,
    },
    "low-drop-rate": {
      laoban: 3,
      shushu: 5,
      hadesen: 1,
      tangwang: 3,
      jiahao: 1,
      shoucangjia: 7,
    },
  },
  "lead-call": {
    "normal-command": {
      menggonglang: 1,
      jiaoguan: 3,
      weilong: 1,
      saiyide: 2,
      hadesen: 3,
      leisi: 1,
      duya: 2,
      demulan: 3,
      mama: 1,
      tangwang: 1,
      jiahao: 3,
      benzhigaoshou: 2,
    },
    "lead-rush": {
      menggonglang: 3,
      jiaoguan: 1,
      weilong: 2,
      saiyide: 3,
      leisi: 3,
      duya: 1,
      demulan: 1,
      tangwang: 1,
      jiahao: 3,
      benzhigaoshou: 1,
    },
    "last-line": {
      menggonglang: 1,
      laoban: 2,
      jiaoguan: 2,
      shushu: 1,
      weilong: 1,
      saiyide: 1,
      mama: 3,
      tangwang: 1,
      jiahao: 3,
      benzhigaoshou: 1,
    },
    "rat-refusal": {
      laoban: 1,
      shushu: 3,
      tujiu: 1,
      tangwang: 3,
      shoucangjia: 3,
    },
    "tax-route": {
      demulan: 2,
      tangwang: 1,
      laobeizha: 3,
      duqiaolai: 6,
    },
  },
  "rich-but-greedy": {
    "call-extract": {
      menggonglang: 1,
      jiaoguan: 2,
      tujiu: 1,
      weilong: 2,
      saiyide: 1,
      hadesen: 2,
      demulan: 3,
      mama: 3,
      jiahao: 1,
      benzhigaoshou: 3,
    },
    "keep-fighting": {
      menggonglang: 3,
      jiaoguan: 1,
      weilong: 1,
      saiyide: 3,
      leisi: 4,
      duya: 2,
      demulan: 1,
      mama: 2,
      jiahao: 3,
      benzhigaoshou: 3,
    },
    "cover-for-team": {
      menggonglang: 1,
      jiaoguan: 3,
      tujiu: 1,
      weilong: 2,
      saiyide: 1,
      hadesen: 1,
      demulan: 3,
      mama: 3,
      jiahao: 1,
      benzhigaoshou: 3,
    },
    "fly-rat": {
      laoban: 3,
      shushu: 3,
      tujiu: 2,
      hadesen: 3,
      leisi: 1,
      duya: 3,
      tangwang: 4,
      jiahao: 1,
      benzhigaoshou: 1,
      shoucangjia: 4,
    },
    "more-money": {
      laoban: 3,
      shushu: 3,
      tujiu: 2,
      hadesen: 1,
      leisi: 2,
      duya: 2,
      tangwang: 3,
      shoucangjia: 6,
    },
  },
  "fixed-team": {
    "reliable-team": {
      menggonglang: 2,
      laoban: 1,
      jiaoguan: 2,
      shushu: 1,
      tujiu: 2,
      weilong: 3,
      saiyide: 2,
      hadesen: 4,
      leisi: 1,
      duya: 2,
      demulan: 4,
      mama: 3,
      laobeizha: 3,
      duqiaolai: 3,
      jiahao: 3,
      benzhigaoshou: 4,
    },
    "rush-brothers": {
      menggonglang: 3,
      jiaoguan: 1,
      tujiu: 1,
      weilong: 3,
      saiyide: 2,
      leisi: 4,
      duya: 1,
      demulan: 1,
      jiahao: 3,
    },
    "loot-rats": {
      shushu: 3,
      tujiu: 1,
      weilong: 1,
      duya: 1,
      tangwang: 4,
      shoucangjia: 3,
    },
    "pay-for-carry": {
      laoban: 6,
    },
    "tax-squad": {
      duya: 2,
      tangwang: 1,
      laobeizha: 3,
      duqiaolai: 6,
    },
  },
  "friendly-rat": {
    "peace-extract": {
      menggonglang: 1,
      laoban: 3,
      jiaoguan: 3,
      shushu: 5,
      tujiu: 1,
      weilong: 2,
      saiyide: 1,
      leisi: 1,
      duya: 3,
      mama: 4,
      tangwang: 3,
      jiahao: 3,
    },
    "shoot-first": {
      tujiu: 2,
      hadesen: 6,
      leisi: 2,
      duya: 3,
      demulan: 2,
      laobeizha: 2,
      duqiaolai: 2,
      benzhigaoshou: 3,
    },
    "betray-at-extract": {
      shushu: 1,
      tujiu: 5,
      leisi: 3,
      duya: 6,
      laobeizha: 1,
      duqiaolai: 3,
    },
    "escort-rat": {
      menggonglang: 3,
      laoban: 3,
      jiaoguan: 4,
      shushu: 2,
      weilong: 4,
      saiyide: 1,
      demulan: 3,
      mama: 5,
      jiahao: 3,
      benzhigaoshou: 2,
    },
    "walk-away": {
      menggonglang: 1,
      laoban: 3,
      jiaoguan: 1,
      shushu: 1,
      tujiu: 2,
      weilong: 1,
      saiyide: 3,
      hadesen: 5,
      duya: 1,
      demulan: 3,
      mama: 2,
      tangwang: 1,
      benzhigaoshou: 2,
      shoucangjia: 1,
    },
  },
  "loot-attitude": {
    "small-to-big": {
      menggonglang: 2,
      laoban: 1,
      shushu: 3,
      weilong: 1,
      tangwang: 3,
      jiahao: 2,
      benzhigaoshou: 2,
      shoucangjia: 6,
    },
    "small-is-enough": {
      shushu: 1,
      tangwang: 3,
      jiahao: -1,
      shoucangjia: 1,
    },
    "enemy-bag-best": {
      menggonglang: 4,
      laoban: 3,
      shushu: 1,
      tujiu: 6,
      weilong: 2,
      tangwang: 1,
      duqiaolai: 3,
      jiahao: 3,
      benzhigaoshou: 3,
    },
    "eat-anything": {
      shushu: 3,
      weilong: 1,
      tangwang: 6,
      jiahao: -1,
      shoucangjia: 2,
    },
    "rich-by-default": {
      laoban: 4,
      shoucangjia: 2,
    },
  },
  "weapon": {
    "cheap-practical": {
      shushu: 3,
      weilong: 1,
      tangwang: 3,
      benzhigaoshou: 1,
    },
    "meta-guns": {
      menggonglang: 9,
      weilong: 2,
      jiahao: 3,
      benzhigaoshou: 2,
    },
    "value-build": {
      menggonglang: 9,
      shushu: 1,
      weilong: 2,
      tangwang: 1,
      jiahao: 2,
      benzhigaoshou: 3,
    },
    "my-own-build": {
      menggonglang: 1,
      weilong: 2,
      tangwang: 1,
      jiahao: 9,
      benzhigaoshou: 3,
    },
    "picked-up": {
      menggonglang: -2,
      shushu: 1,
      tangwang: 5,
      jiahao: -2,
      benzhigaoshou: -2,
      shoucangjia: 3,
    },
  },
};
