import {
  CORE_PERSONA_IDS,
  EXTRA_BASE_PERSONA_IDS,
  PROJECTION_PERSONA_IDS,
  type CorePersonaId,
  type ExtraBasePersonaId,
  type Persona,
  type ProjectionPersonaId,
} from "./types";

export const personas: Persona[] = [
  {
    id: "menggonglang",
    layer: "core",
    slug: "menggongjiang",
    shortCode: "YANZ-U",
    nameCn: "猛攻将",
    nameEn: "Assault Warlord",
    roleLabel: "高压突进型",
    tone: "signal",
    summary: "你偏好主动开火和强压节奏，宁可先打再修正。",
    resultIntro: "今天你的底色是猛攻将：你靠主动权吃饭。",
    playstyle: "高战备、高交火频率、先手突破。",
    tacticalProfile: "擅长用压制创造机会，短板是止损慢。",
    strengths: ["敢打先手", "推进速度快", "压制力强"],
    blindSpots: ["容易上头", "成本波动大", "高估硬刚收益"],
    signatureLine: "来都来了，狠狠干。",
    visualLabel: "正面压制",
    signalWords: ["先手", "全装", "狠狠干"],
    notMixWith: ["本质高手"],
    dimensionProfile: { combat: 7, team: 4, loot: 4, tactics: 4, rational: 4, emotion: 7 },
    meaningProfile: { kill: 5, destruction: 3, belief: 1 },
  },
  {
    id: "laoban",
    layer: "core",
    slug: "laoban",
    shortCode: "BOSS",
    nameCn: "老板",
    nameEn: "The Boss",
    roleLabel: "资源调度型",
    tone: "slate",
    summary: "你更看重收益兑现，不愿为无意义风险买单。",
    resultIntro: "今天你的底色是老板：风险外包，稳定吃分。",
    playstyle: "稳扎稳打，优先保收益和撤离。",
    tacticalProfile: "擅长成本控制和节奏管理。",
    strengths: ["止损稳", "性价比高", "长期资产稳定"],
    blindSpots: ["主动开局弱", "依赖队友开口", "容易被误解为保守"],
    signatureLine: "这把先稳，别炸单。",
    visualLabel: "收益调度",
    signalWords: ["保本", "止损", "撤离兑现"],
    notMixWith: ["唐王大人", "收藏家"],
    dimensionProfile: { combat: 3, team: 6, loot: 9, tactics: 4, rational: 7, emotion: 4 },
    meaningProfile: { profit: 5, efficiency: 3, collection: 1 },
  },
  {
    id: "shushu",
    layer: "core",
    slug: "shushu",
    shortCode: "MOUS-E",
    nameCn: "鼠鼠",
    nameEn: "Loot Rat",
    roleLabel: "生存摸金型",
    tone: "slate",
    summary: "你想富也怕死，重点是活着把收益带出去。",
    resultIntro: "今天你的底色是鼠鼠：撤离成功比击杀更重要。",
    playstyle: "避战、绕路、观察、保本。",
    tacticalProfile: "强在生存和收益嗅觉，弱在硬碰上限。",
    strengths: ["撤离意识强", "保本能力高", "风险判断敏锐"],
    blindSpots: ["错过可打窗口", "被动节奏偏多", "上限依赖局势"],
    signatureLine: "先飞鼠，活着再说。",
    visualLabel: "静撤保货",
    signalWords: ["避战", "保本", "飞鼠"],
    notMixWith: ["秃鹫", "收藏家"],
    dimensionProfile: { combat: 4, team: 4, loot: 8, tactics: 5, rational: 5, emotion: 7 },
    meaningProfile: { profit: 5, efficiency: 2, fate: 1 },
  },
  {
    id: "benzhigaoshou",
    layer: "core",
    slug: "benzhigaoshou",
    shortCode: "NIUB-I",
    nameCn: "本质高手",
    nameEn: "Pure Operator",
    roleLabel: "读局执行型",
    tone: "mint",
    summary: "你擅长把复杂局面拆成可执行动作，再稳定落地。",
    resultIntro: "今天你的底色是本质高手：你靠理解赢，不靠运气。",
    playstyle: "先读局，再选点，再执行。",
    tacticalProfile: "理性与战术双高，情绪波动低。",
    strengths: ["读局快", "执行稳", "处理复杂局面强"],
    blindSpots: ["标准高", "对失误敏感", "容错耐心偏低"],
    signatureLine: "先看明白，再打明白。",
    visualLabel: "局势掌控",
    signalWords: ["读局", "处理", "最优动作"],
    notMixWith: ["猛攻将", "嘉豪"],
    dimensionProfile: { combat: 8, team: 7, loot: 3, tactics: 10, rational: 10, emotion: 2 },
    meaningProfile: { control: 5, efficiency: 3, command: 2 },
  },
  {
    id: "mama",
    layer: "core",
    slug: "mama",
    shortCode: "MOMM-Y",
    nameCn: "妈妈",
    nameEn: "Caretaker",
    roleLabel: "照顾托底型",
    tone: "mint",
    summary: "你会优先看队友状态，主动托底补位。",
    resultIntro: "今天你的底色是妈妈：你是队伍下限的保护层。",
    playstyle: "拉人、补给、补位、稳氛围。",
    tacticalProfile: "团队责任拉满，推进更偏稳态。",
    strengths: ["托底稳定", "资源分配好", "团队粘合强"],
    blindSpots: ["容易过度照顾", "牺牲个人节奏", "不擅长果断放弃"],
    signatureLine: "别慌，我先把人稳住。",
    visualLabel: "队内托底",
    signalWords: ["拉人", "补位", "托底"],
    notMixWith: ["教官"],
    dimensionProfile: { combat: 4, team: 9, loot: 5, tactics: 6, rational: 5, emotion: 8 },
    meaningProfile: { care: 5, guardianship: 3, command: 2 },
  },
  {
    id: "tujiu",
    layer: "core",
    slug: "tujiu",
    shortCode: "TUJI-U",
    nameCn: "秃鹫",
    nameEn: "Scavenger Vulture",
    roleLabel: "残局收割型",
    tone: "slate",
    summary: "你擅长闻味进场，在混战边缘吃到最大收益。",
    resultIntro: "今天你的底色是秃鹫：你会抓别人打完后的真空期。",
    playstyle: "后手入场、坐收残局、效率舔包。",
    tacticalProfile: "收益高、站位刁，团队责任偏低。",
    strengths: ["残局嗅觉强", "收割效率高", "切入窗口准"],
    blindSpots: ["容易贪一口", "团内信任成本高", "正面对枪上限一般"],
    signatureLine: "闻到味了，再吃两口。",
    visualLabel: "残局收割",
    signalWords: ["后手", "舔包", "坐收渔利"],
    notMixWith: ["鼠鼠", "堵桥来"],
    dimensionProfile: { combat: 3, team: 2, loot: 8, tactics: 9, rational: 9, emotion: 2 },
    meaningProfile: { profit: 4, disruption: 2, fate: 1 },
  },
  {
    id: "shoucangjia",
    layer: "core",
    slug: "shoucangjia",
    shortCode: "RICH",
    nameCn: "收藏家",
    nameEn: "Collector",
    roleLabel: "长期囤积型",
    tone: "slate",
    summary: "你追求的是占有和积累，不是短期爆利。",
    resultIntro: "今天你的底色是收藏家：你在收集长期成果。",
    playstyle: "目标明确，围绕高价值收藏品行动。",
    tacticalProfile: "摸金高、交火低，稳定推进长期收益。",
    strengths: ["长期目标稳定", "价值判断准", "节奏不易失控"],
    blindSpots: ["短期爆发弱", "可能错过交火收益", "执念过强会僵化"],
    signatureLine: "这件得进收藏室。",
    visualLabel: "图鉴执念",
    signalWords: ["图鉴", "收藏", "长期成果"],
    notMixWith: ["鼠鼠", "老板"],
    dimensionProfile: { combat: 1, team: 3, loot: 10, tactics: 3, rational: 8, emotion: 4 },
    meaningProfile: { collection: 5, profit: 2, style: 1 },
  },
  {
    id: "weilong",
    layer: "projection",
    slug: "weilong",
    shortCode: "LONG",
    nameCn: "威龙",
    nameEn: "Viper Breach",
    roleLabel: "开口担责型",
    tone: "signal",
    summary: "你会在关键时刻顶上去，用行动带动全队。",
    resultIntro: "今天你的匹配偏向威龙：你愿意扛第一下风险。",
    playstyle: "带头冲、抢开口、压枪线。",
    tacticalProfile: "推进积极，执行偏动作派。",
    strengths: ["带头能力强", "打破僵局快", "队友信号明确"],
    blindSpots: ["细节管理弱于教官", "容易情绪推进", "个人损耗偏高"],
    signatureLine: "我来开口，你们跟。",
    visualLabel: "开路担责",
    signalWords: ["开口", "先顶", "破局"],
    notMixWith: ["教官"],
    dimensionProfile: { combat: 8, team: 7, loot: 4, tactics: 6, rational: 4, emotion: 8 },
    meaningProfile: { kill: 3, guardianship: 3, command: 1 },
  },
  {
    id: "jiaoguan",
    layer: "projection",
    slug: "jiaoguan",
    shortCode: "DADD-Y",
    nameCn: "教官",
    nameEn: "Instructor",
    roleLabel: "秩序带队型",
    tone: "mint",
    summary: "你偏向统一信息和分工，追求团队最优。",
    resultIntro: "今天你的匹配偏向教官：你在管理节奏。",
    playstyle: "口令清晰，职责明确，推进有序。",
    tacticalProfile: "团队、战术、理性都高。",
    strengths: ["全队协同强", "信息整合快", "节奏掌控稳"],
    blindSpots: ["压迫感偏强", "对低配合容忍低", "柔性沟通不足"],
    signatureLine: "信息对齐，按我节奏走。",
    visualLabel: "秩序指挥",
    signalWords: ["对齐", "分工", "节奏"],
    notMixWith: ["妈妈", "威龙", "德穆兰"],
    dimensionProfile: { combat: 5, team: 9, loot: 5, tactics: 8, rational: 8, emotion: 5 },
    meaningProfile: { command: 5, care: 2, guardianship: 2 },
  },
  {
    id: "saiyide",
    layer: "projection",
    slug: "saiyide",
    shortCode: "SAEE-D",
    nameCn: "赛伊德",
    nameEn: "Saeed",
    roleLabel: "立场狠人型",
    tone: "signal",
    summary: "你会带着情绪立场推进，不愿让自己人白给。",
    resultIntro: "今天你的匹配偏向赛伊德：你的狠是有方向的。",
    playstyle: "护人、强推、关键局不退。",
    tacticalProfile: "情绪驱动高，但不是无脑冲。",
    strengths: ["保护欲强", "关键局敢顶", "团内信念稳定"],
    blindSpots: ["容易偏执", "容错下降", "与纯理性流摩擦高"],
    signatureLine: "自己人不能白死。",
    visualLabel: "立场推进",
    signalWords: ["护自己人", "信念", "硬推"],
    notMixWith: ["雷斯", "猛攻将"],
    dimensionProfile: { combat: 8, team: 6, loot: 3, tactics: 4, rational: 3, emotion: 9 },
    meaningProfile: { belief: 5, guardianship: 3, kill: 1 },
  },
  {
    id: "demulan",
    layer: "projection",
    slug: "demulan",
    shortCode: "CTRL",
    nameCn: "德穆兰",
    nameEn: "De Mulan",
    roleLabel: "上位护队型",
    tone: "mint",
    summary: "你会站在更高位规划，保证自己队伍不吃亏。",
    resultIntro: "今天你的匹配偏向德穆兰：你在统筹资源与保护边界。",
    playstyle: "先站位、后分工、再推进。",
    tacticalProfile: "秩序与保护并重，边界感很强。",
    strengths: ["统筹能力强", "高压局稳定", "保队效率高"],
    blindSpots: ["上下位感明显", "外部协作弹性小", "温和度较低"],
    signatureLine: "我的人不能白亏。",
    visualLabel: "统筹护队",
    signalWords: ["统筹", "保护", "站位"],
    notMixWith: ["教官", "妈妈"],
    dimensionProfile: { combat: 3, team: 8, loot: 4, tactics: 9, rational: 7, emotion: 6 },
    meaningProfile: { guardianship: 5, command: 3, care: 1 },
  },
  {
    id: "duya",
    layer: "projection",
    slug: "duya",
    shortCode: "DUYA",
    nameCn: "渡鸦",
    nameEn: "Raven",
    roleLabel: "戏剧搅局型",
    tone: "signal",
    summary: "你喜欢变局和反转，乐趣是把局面改写成自己的剧本。",
    resultIntro: "今天你的匹配偏向渡鸦：你天生有搅局审美。",
    playstyle: "背刺、反切、创造混乱窗口。",
    tacticalProfile: "战术高、团队低，风格化明显。",
    strengths: ["变局能力强", "边角切入准", "心理压制明显"],
    blindSpots: ["团队舒适度低", "稳定性波动", "容易被误判为纯阴"],
    signatureLine: "局味变了，戏才开场。",
    visualLabel: "戏剧搅局",
    signalWords: ["搅局", "反转", "背刺"],
    notMixWith: ["雷斯", "老贝榨"],
    dimensionProfile: { combat: 8, team: 2, loot: 5, tactics: 9, rational: 2, emotion: 9 },
    meaningProfile: { disruption: 5, style: 2, torment: 1 },
  },
  {
    id: "hadesen",
    layer: "projection",
    slug: "hadesen",
    shortCode: "GOAL",
    nameCn: "哈德森",
    nameEn: "Hudson",
    roleLabel: "效率极解型",
    tone: "mint",
    summary: "你偏好最优解，先止损再推进。",
    resultIntro: "今天你的匹配偏向哈德森：你在追求可执行结果。",
    playstyle: "算成本、算路径、算代价。",
    tacticalProfile: "战术理性拉满，情绪驱动最低。",
    strengths: ["止损快", "决策清", "资源利用率高"],
    blindSpots: ["人情耐受低", "显冷", "可能过度结果化"],
    signatureLine: "别浪费，按最优解走。",
    visualLabel: "最优解驱动",
    signalWords: ["最优解", "止损", "效率"],
    notMixWith: ["教官", "德穆兰"],
    dimensionProfile: { combat: 5, team: 4, loot: 4, tactics: 10, rational: 10, emotion: 3 },
    meaningProfile: { efficiency: 5, control: 2, command: 1 },
  },
  {
    id: "leisi",
    layer: "projection",
    slug: "leisi",
    shortCode: "MAMBA",
    nameCn: "雷斯",
    nameEn: "Reyes",
    roleLabel: "冲撞破坏型",
    tone: "signal",
    summary: "你要的是存在感和冲撞感，能把僵局硬撞开。",
    resultIntro: "今天你的匹配偏向雷斯：你是高冲击破坏者。",
    playstyle: "强压、硬顶、破平衡。",
    tacticalProfile: "交战和情绪极高，理性与团队较低。",
    strengths: ["冲击力极强", "僵局破拆快", "压迫感高"],
    blindSpots: ["稳定性低", "容错低", "容易全场公敌"],
    signatureLine: "不舒服就对了。",
    visualLabel: "冲撞破坏",
    signalWords: ["硬撞", "破坏", "存在感"],
    notMixWith: ["赛伊德", "渡鸦", "老贝榨"],
    dimensionProfile: { combat: 10, team: 2, loot: 5, tactics: 2, rational: 3, emotion: 10 },
    meaningProfile: { destruction: 5, kill: 2, disruption: 1 },
  },
  {
    id: "jiahao",
    layer: "base_extra",
    slug: "jiahao",
    shortCode: "HAO",
    nameCn: "嘉豪",
    nameEn: "Style Lab",
    roleLabel: "风格表达型",
    tone: "mint",
    summary: "你不只追求赢，还要赢得有味道。",
    resultIntro: "今天你的底色偏嘉豪：你有强烈个人配置审美。",
    playstyle: "顺手理解 + 个性配置 + 审美驱动。",
    tacticalProfile: "战术中高，风格动机明显。",
    strengths: ["个性稳定", "手感调优强", "表达感鲜明"],
    blindSpots: ["可能过度坚持风格", "客观性波动", "易忽略版本收益"],
    signatureLine: "帅和手感都要。",
    visualLabel: "自我风格",
    signalWords: ["风格", "理解", "手感"],
    notMixWith: ["本质高手"],
    dimensionProfile: { combat: 8, team: 4, loot: 4, tactics: 6, rational: 7, emotion: 9 },
    meaningProfile: { style: 5, control: 2, efficiency: 1 },
  },
  {
    id: "laobeizha",
    layer: "base_extra",
    slug: "laobeizha",
    shortCode: "BOMB",
    nameCn: "老贝榨",
    nameEn: "Bomb Tormentor",
    roleLabel: "折磨技师型",
    tone: "signal",
    summary: "你不执着一波硬刚，你的乐趣是把对面的舒适区一点点拆掉。",
    resultIntro: "今天你的底色偏老贝榨：你靠持续折磨和节奏压制拿主动。",
    playstyle: "爆炸物、范围压制、骚扰道具连用，先让对面难受再终结。",
    tacticalProfile: "擅长把正常交火变成环境灾害，核心是过程压迫而非瞬间击杀。",
    strengths: ["持续压迫强", "控区拖节奏强", "能快速放大对手失误"],
    blindSpots: ["容易沉迷折磨感而偏离胜利目标", "终结节奏偏慢", "被夹击风险上升"],
    signatureLine: "先让你难受，再让你出局。",
    visualLabel: "持续折磨",
    signalWords: ["折磨", "爆炸物", "红温"],
    notMixWith: ["雷斯", "渡鸦"],
    dimensionProfile: { combat: 4, team: 3, loot: 5, tactics: 9, rational: 6, emotion: 7 },
    meaningProfile: { torment: 5, disruption: 2, taxation: 1 },
  },
  {
    id: "duqiaolai",
    layer: "base_extra",
    slug: "duqiaolai",
    shortCode: "CSGO",
    nameCn: "堵桥来",
    nameEn: "Tax Route Controller",
    roleLabel: "撤离收税型",
    tone: "signal",
    summary: "你擅长把桥口和撤离线变成收费口，别人迟早要从你这过。",
    resultIntro: "今天你的底色偏堵桥来：你用地图规则而不是对枪欲望主导收益。",
    playstyle: "卡桥、封口、控撤离、收过路税。",
    tacticalProfile: "以空间控制替代正面缠斗，耐心和点位经营决定上限。",
    strengths: ["地形理解强", "卡位耐心高", "撤离路径压制强"],
    blindSpots: ["容易困在舒适点位", "机动转点能力下降", "空等导致收益波动"],
    signatureLine: "你们总得撤离。",
    visualLabel: "空间税务",
    signalWords: ["堵桥", "收税", "撤离口"],
    notMixWith: ["秃鹫", "老贝榨"],
    dimensionProfile: { combat: 4, team: 3, loot: 6, tactics: 9, rational: 7, emotion: 6 },
    meaningProfile: { taxation: 5, torment: 2, control: 2 },
  },
  {
    id: "tangwang",
    layer: "base_extra",
    slug: "tangwang",
    shortCode: "TWDR",
    nameCn: "唐王大人",
    nameEn: "Blessed Rat",
    roleLabel: "玄学爆率型",
    tone: "mint",
    summary: "你可能操作一般，但收益命中率离谱地高。",
    resultIntro: "今天你的底色偏唐王大人：系统在给你发惊喜。",
    playstyle: "轻对抗、重摸金、靠运气窗口拿收益。",
    tacticalProfile: "摸金高，操作压强低，玄学味重。",
    strengths: ["收益惊喜高", "轻松感强", "能带活队内氛围"],
    blindSpots: ["稳定上限低", "误判自我实力", "高压局容错差"],
    signatureLine: "枪法一般，但总能富。",
    visualLabel: "命格加成",
    signalWords: ["玄学", "爆率", "命格"],
    notMixWith: ["老板", "鼠鼠"],
    dimensionProfile: { combat: 2, team: 2, loot: 10, tactics: 3, rational: 4, emotion: 5 },
    meaningProfile: { fate: 5, profit: 3, collection: 1 },
  },
];

export const personasById = Object.fromEntries(
  personas.map((persona) => [persona.id, persona]),
) as Record<Persona["id"], Persona>;

export const corePersonas = CORE_PERSONA_IDS.map((id) => personasById[id as CorePersonaId]);
export const projectionPersonas = PROJECTION_PERSONA_IDS.map(
  (id) => personasById[id as ProjectionPersonaId],
);
export const extraBasePersonas = EXTRA_BASE_PERSONA_IDS.map(
  (id) => personasById[id as ExtraBasePersonaId],
);
