import type { Question, QuestionId } from "./types";

// TODO:
// 1. 西普坝王、夺舍的狼、林树、昊天等特殊彩蛋仍在 todo.md 迭代规则，当前先不接入评分引擎。
// 2. 资产题中的“经济管理能力”暂用理性/战术/meaning 组合近似表达，后续可独立建模。
// 3. 题目内容和发题顺序分离；实际顺序由 questionFlowOrder 控制。
const questionBank: Question[] = [
  {
    id: "gunfire",
    prompt: "当不远处传来激烈交火声，你会选择？",
    brief: "这题先测你是想打、想看、还是想躲。",
    options: [
      {
        id: "read-and-join",
        label: "先听信息，判断能不能参战，有机会再上",
        description: "脑子先到位，再决定人要不要进场。",
        dimensionDeltas: { tactics: 2, combat: 1, rational: 1 },
        meaningDeltas: { control: 1 },
        personaSignals: { benzhigaoshou: 2, weilong: 1, jiaoguan: 1 },
      },
      {
        id: "late-loot",
        label: "静摸，随时出击坐收渔翁之利",
        description: "不急着做第一个进门的人，但很愿意做最后吃包的人。",
        dimensionDeltas: { loot: 2, tactics: 1, rational: 1, combat: -1 },
        meaningDeltas: { profit: 1, disruption: 1 },
        personaSignals: { tujiu: 2, duya: 1 },
        easterEggSignals: { duqiaolai: 0.5 },
      },
      {
        id: "rush-now",
        label: "还在等什么，跟他们爆了",
        description: "有枪声就是信号，狠狠干才像进图。",
        dimensionDeltas: { combat: 2, emotion: 2, rational: -1 },
        meaningDeltas: { kill: 2, destruction: 1 },
        personaSignals: { menggonglang: 2, leisi: 2, saiyide: 2, weilong: 1 },
      },
      {
        id: "call-the-team",
        label: "语音联系队友，等队友再说",
        description: "先把人叫齐，再看这波怎么吃。",
        dimensionDeltas: { team: 2, rational: 1, tactics: 1 },
        meaningDeltas: { care: 1, command: 1 },
        personaSignals: { mama: 2, jiaoguan: 2, weilong: 1 },
      },
      {
        id: "ignore-for-loot",
        label: "关我啥事，居然有露天小紫",
        description: "枪声再热，也没有面前的资源更真。",
        dimensionDeltas: { loot: 2, combat: -2 },
        meaningDeltas: { profit: 2, collection: 1, fate: 1 },
        personaSignals: { shoucangjia: 2, shushu: 2 },
        easterEggSignals: { tangwang: 1 },
      },
    ],
  },
  {
    id: "after-fight",
    prompt: "你和队友刚刚打完一队，盒子还没吃，远处又传来脚步，你会怎么处理？",
    brief: "这里测的是你面对二次接敌时，优先保什么。",
    options: [
      {
        id: "leave-with-profit",
        label: "三十六计走为上计，枪捡走花来！",
        description: "见好就收，不给下一队白打你的机会。",
        dimensionDeltas: { loot: 2, combat: -2, rational: 1, tactics: 1 },
        meaningDeltas: { profit: 2 },
        personaSignals: { shushu: 2, shoucangjia: 2, laoban: 2 },
      },
      {
        id: "hold-angles",
        label: "找掩体架枪，听信息",
        description: "这不是怂，是把脑子先摆到枪前面。",
        dimensionDeltas: { tactics: 2, rational: 2, combat: 1 },
        meaningDeltas: { control: 2 },
        personaSignals: { benzhigaoshou: 2, hadesen: 2, jiaoguan: 2 },
      },
      {
        id: "fight-next",
        label: "盒子等会再说，来一个我打一个",
        description: "盒子不会跑，人不狠狠干就没意思了。",
        dimensionDeltas: { combat: 2, emotion: 1, team: 1 },
        meaningDeltas: { kill: 2 },
        personaSignals: { menggonglang: 2, saiyide: 2, leisi: 2 },
      },
      {
        id: "stabilize-squad",
        label: "看队友位置，并确保全员状态健康",
        description: "这波都打赢了，就别让队伍死在细节里。",
        dimensionDeltas: { team: 2, rational: 1, tactics: 1 },
        meaningDeltas: { care: 1, command: 1, guardianship: 1 },
        personaSignals: { mama: 2, jiaoguan: 2, demulan: 2 },
      },
      {
        id: "loot-two-more",
        label: "先让我吃两口热饭",
        description: "你对再舔两口这件事，总有一点致命信心。",
        dimensionDeltas: { loot: 2, rational: -1, combat: -1 },
        meaningDeltas: { profit: 2, collection: 1, fate: 1 },
        personaSignals: { tujiu: 2, shoucangjia: 1 },
        easterEggSignals: { tangwang: 1 },
      },
    ],
  },
  {
    id: "loadout",
    prompt: "进图前，队友问你这把准备怎么起装，你更像哪一种？",
    brief: "这题最容易把“理性”“上头”“风格”三件事拆开。",
    options: [
      {
        id: "budget-smart",
        label: "该省省该花花，卡好战备就进图",
        description: "不是穷，是成本控制型起装。",
        dimensionDeltas: { rational: 2, tactics: 1, loot: 1, combat: -1 },
        meaningDeltas: { efficiency: 1, profit: 1 },
        personaSignals: { laoban: 2, shushu: 2, hadesen: 1 },
      },
      {
        id: "full-send",
        label: "全装五头五甲满改枪，猛攻",
        description: "这局就是要狠狠干，别问为什么。",
        dimensionDeltas: { emotion: 2, combat: 2, tactics: -1, loot: -1 },
        meaningDeltas: { kill: 3, destruction: 1 },
        personaSignals: { menggonglang: 2, leisi: 2, saiyide: 1 },
      },
      {
        id: "style-build",
        label: "必须轻语闪电 M14 老赛甲，4:3 彦祖威龙，我的态度",
        description: "不是非主流，是带理解的风格执念。",
        dimensionDeltas: { rational: 1, tactics: 1, combat: 1 },
        meaningDeltas: { style: 4, control: 1 },
        personaSignals: { benzhigaoshou: 1, weilong: 1 },
        easterEggSignals: { jiahao: 2 },
      },
      {
        id: "torment-kit",
        label: "维克托、G18、QCQ171，花来足浴顶级技师",
        description: "正面对枪不是唯一乐趣，恶心人也是一种艺术。",
        dimensionDeltas: { emotion: 1, tactics: 1, combat: 1 },
        meaningDeltas: { torment: 4, disruption: 1 },
        personaSignals: { duya: 1 },
        easterEggSignals: { laobeizha: 2, duqiaolai: 0.5 },
      },
      {
        id: "stable-kit",
        label: "枪用自己最顺手的，各种资源要带够",
        description: "别让细节拖后腿，稳定发挥才是王道。",
        dimensionDeltas: { tactics: 2, rational: 2, combat: 1 },
        meaningDeltas: { control: 2, efficiency: 1 },
        personaSignals: { benzhigaoshou: 2, hadesen: 2, jiaoguan: 1 },
      },
    ],
  },
  {
    id: "backpack",
    prompt: "平时进机密以上难度的图，你会带什么包？",
    brief: "这题表面是包，实际测的是你怎么理解风险、效率和欲望。",
    options: [
      {
        id: "ga-20",
        label: "20 格 GA 野战背包",
        description: "够用、顺手、实战优先。",
        dimensionDeltas: { loot: 1, tactics: 2, rational: 2, combat: 1 },
        meaningDeltas: { efficiency: 1, control: 1 },
        personaSignals: { benzhigaoshou: 2, shushu: 1, weilong: 1 },
      },
      {
        id: "take-from-bots",
        label: "人机身上不是有包吗",
        description: "先进图再说，资源到场上解决。",
        dimensionDeltas: { combat: 1, loot: 1, rational: -1, emotion: 1 },
        meaningDeltas: { fate: 1, kill: 1 },
        personaSignals: { menggonglang: 1, leisi: 1 },
        easterEggSignals: { tangwang: 1 },
      },
      {
        id: "green-15",
        label: "谁懂 15 格绿包",
        description: "极限省钱，极限保本，极限想活。",
        dimensionDeltas: { loot: 2, rational: 1, combat: -2, tactics: 1 },
        meaningDeltas: { profit: 2, efficiency: 1 },
        personaSignals: { shushu: 2, laoban: 2 },
        easterEggSignals: { tangwang: 0.5 },
      },
      {
        id: "gold-30",
        label: "必须 30 大金包",
        description: "不是贪，是会算包位、枪位和效率。",
        dimensionDeltas: { loot: 2, tactics: 2, rational: 2, combat: 1 },
        meaningDeltas: { efficiency: 2, profit: 1 },
        personaSignals: { benzhigaoshou: 2, hadesen: 2, laoban: 2, tujiu: 1 },
        easterEggSignals: { jiahao: 0.5 },
      },
      {
        id: "red-45",
        label: "吞天 45 大金包常伴吾身",
        description: "这不是效率，是欲望，是全都要。",
        dimensionDeltas: { loot: 3, rational: -1, emotion: 1, combat: -1 },
        meaningDeltas: { collection: 2, profit: 1, fate: 1 },
        personaSignals: { shoucangjia: 2, laoban: 2, shushu: 1 },
        easterEggSignals: { tangwang: 1 },
      },
    ],
  },
  {
    id: "operator",
    prompt: "你最喜欢用的干员类型是？",
    brief: "这一题会把你默认想站的位置暴露得很明显。",
    options: [
      {
        id: "assault",
        label: "突击",
        description: "我来开门，我来顶，口子我来撕。",
        dimensionDeltas: { combat: 2, team: 1, tactics: 1, emotion: 1 },
        meaningDeltas: { kill: 2, guardianship: 1 },
        personaSignals: { weilong: 2, menggonglang: 2, benzhigaoshou: 1 },
      },
      {
        id: "recon",
        label: "侦查",
        description: "信息、节奏、背刺，都是赢法的一部分。",
        dimensionDeltas: { combat: 1, tactics: 2, rational: 1, team: 1 },
        meaningDeltas: { disruption: 2, control: 1 },
        personaSignals: { benzhigaoshou: 2, duya: 2, tujiu: 1 },
      },
      {
        id: "support",
        label: "支援",
        description: "托底、补位、稳住全队，这位置有存在感。",
        dimensionDeltas: { team: 3, tactics: 1, rational: 1, combat: -1 },
        meaningDeltas: { care: 2, guardianship: 1 },
        personaSignals: { mama: 2, jiaoguan: 2, demulan: 2 },
      },
      {
        id: "engineer",
        label: "工程",
        description: "我喜欢用机制和空间，让别人难受。",
        dimensionDeltas: { tactics: 2, rational: 2, combat: 1, team: 1 },
        meaningDeltas: { efficiency: 1, taxation: 1, torment: 1, control: 1 },
        personaSignals: { hadesen: 2, jiaoguan: 1 },
        easterEggSignals: { duqiaolai: 1, laobeizha: 1 },
      },
      {
        id: "saiyide",
        label: "赛伊德",
        description: "不是职业偏好，是人格偏好，我就认这个味。",
        dimensionDeltas: { combat: 2, team: 1, emotion: 2, tactics: 1 },
        meaningDeltas: { belief: 2, kill: 1, guardianship: 1 },
        personaSignals: { saiyide: 4, weilong: 1, menggonglang: 1 },
      },
    ],
  },
  {
    id: "map",
    prompt: "你最喜欢的地图是？",
    brief: "地图偏好会把你的节奏和乐趣来源一起拖出来。",
    options: [
      {
        id: "dam",
        label: "零号大坝",
        description: "什么都能来一点，局面永远不会太单调。",
        dimensionDeltas: { combat: 1, team: 1, loot: 1, tactics: 1 },
        personaSignals: { weilong: 2, shushu: 2, laoban: 2, saiyide: 2 },
      },
      {
        id: "valley",
        label: "长弓溪谷",
        description: "慢一点、稳一点、摸得舒服一点。",
        dimensionDeltas: { loot: 2, combat: -1, tactics: 1, rational: 1 },
        meaningDeltas: { profit: 2 },
        personaSignals: { shushu: 2, shoucangjia: 2, laoban: 2, leisi: 1 },
        easterEggSignals: { laobeizha: 1 },
      },
      {
        id: "bakash",
        label: "巴克什",
        description: "强度够高，狠狠干和判断都能打出来。",
        dimensionDeltas: { combat: 2, tactics: 2, rational: 1, emotion: 1 },
        meaningDeltas: { control: 2, kill: 1 },
        personaSignals: { benzhigaoshou: 2, menggonglang: 2, weilong: 2, leisi: 1 },
      },
      {
        id: "space-base",
        label: "航天基地",
        description: "高压撤离、效率处理、每一步都要算。",
        dimensionDeltas: { tactics: 2, rational: 2, loot: 1, combat: 1 },
        meaningDeltas: { efficiency: 2, taxation: 1 },
        personaSignals: { hadesen: 3, demulan: 3, benzhigaoshou: 2 },
        easterEggSignals: { duqiaolai: 1 },
      },
      {
        id: "prison",
        label: "潮汐监狱",
        description: "越混沌越好，最好局面还能当场变味。",
        dimensionDeltas: { combat: 1, tactics: 2, emotion: 1, team: -1 },
        meaningDeltas: { disruption: 3 },
        personaSignals: { duya: 4, leisi: 2, saiyide: 1 },
      },
    ],
  },
  {
    id: "difficulty",
    prompt: "你最常玩的难度是？",
    brief: "这题主要看你对强度、风险和收益平衡的默认选择。",
    options: [
      {
        id: "normal",
        label: "常规",
        description: "轻松进图，低压摸金，稳一点更舒服。",
        dimensionDeltas: { combat: -1, loot: 1, rational: 1, tactics: -1 },
        meaningDeltas: { profit: 1, fate: 1 },
        personaSignals: { shushu: 2, laoban: 2, shoucangjia: 1 },
        easterEggSignals: { tangwang: 1 },
      },
      {
        id: "confidential",
        label: "机密",
        description: "均衡节奏，什么都能打一打。",
        dimensionDeltas: { combat: 1, loot: 1, tactics: 1, rational: 1 },
        meaningDeltas: { control: 1, efficiency: 1 },
        personaSignals: { benzhigaoshou: 2, weilong: 1, mama: 1, jiaoguan: 1 },
      },
      {
        id: "classified",
        label: "绝密",
        description: "高压高强度，风险和收益都拉满。",
        dimensionDeltas: { combat: 2, tactics: 2, rational: 1, emotion: 1 },
        meaningDeltas: { kill: 1, control: 1 },
        personaSignals: { benzhigaoshou: 2, menggonglang: 2, hadesen: 2, demulan: 2, weilong: 1 },
      },
    ],
  },
  {
    id: "single-extract-priority",
    prompt: "队伍里如果只能有一个人撤出去，你更希望是谁？",
    brief: "这题测的是你在极限资源下的价值排序。",
    options: [
      {
        id: "me-first",
        label: "当然是我，至少先保一个活口和信息出去",
        description: "不是逞强，是自保优先。",
        dimensionDeltas: { team: -2, loot: 1, rational: -1, emotion: 1 },
        meaningDeltas: { profit: 1, fate: 1 },
        personaSignals: { shushu: 2, laoban: 2, leisi: 1 },
      },
      {
        id: "teammate-first",
        label: "队友能撤出去就好",
        description: "你会把人放在收益之前。",
        dimensionDeltas: { team: 2, emotion: 1, combat: -1, loot: -1 },
        meaningDeltas: { care: 2, guardianship: 1 },
        personaSignals: { mama: 2, weilong: 1, saiyide: 1 },
      },
      {
        id: "loot-carrier",
        label: "摸到大货的那个人",
        description: "谁带着最关键资源，谁先走。",
        dimensionDeltas: { loot: 2, rational: 2, team: -1, tactics: 1 },
        meaningDeltas: { profit: 2, collection: 1 },
        personaSignals: { laoban: 2, shushu: 2, shoucangjia: 1 },
        easterEggSignals: { tangwang: 0.5 },
      },
      {
        id: "big-safe",
        label: "保险箱最大的那个人",
        description: "比起情绪，你更信效率和承载能力。",
        dimensionDeltas: { rational: 2, tactics: 2, loot: 1, team: -1 },
        meaningDeltas: { efficiency: 2, control: 1 },
        personaSignals: { hadesen: 2, demulan: 2, benzhigaoshou: 2 },
      },
      {
        id: "all-extract",
        label: "我会想办法让所有人一起撤出去",
        description: "你倾向于主动兜底，不接受放弃队友。",
        dimensionDeltas: { team: 3, tactics: 2, rational: 1, loot: -1 },
        meaningDeltas: { command: 2, care: 2, guardianship: 1 },
        personaSignals: { jiaoguan: 2, mama: 2, weilong: 1, demulan: 1 },
      },
    ],
  },
  {
    id: "asset-level",
    prompt: "你平时最常处在什么资产水平？",
    brief: "这题主要反映仓库波动、风格稳定性和收益习惯。",
    options: [
      {
        id: "under-10m",
        label: "10M 以内",
        description: "仓库经常坐过山车，今天富明天穷。",
        dimensionDeltas: { loot: 1, rational: -1, emotion: 1 },
        meaningDeltas: { fate: 2, profit: 1 },
        personaSignals: { menggonglang: 2, shushu: 2 },
        easterEggSignals: { tangwang: 1 },
      },
      {
        id: "10m-50m",
        label: "10M - 50M",
        description: "慢慢富，保本和稳定优先。",
        dimensionDeltas: { loot: 2, rational: 1, tactics: 1 },
        meaningDeltas: { profit: 2, efficiency: 1 },
        personaSignals: { shushu: 2, laoban: 2 },
      },
      {
        id: "50m-100m",
        label: "50M - 100M",
        description: "节奏平衡，资产稳步积累。",
        dimensionDeltas: { loot: 2, rational: 2, tactics: 1 },
        meaningDeltas: { profit: 2, efficiency: 1 },
        personaSignals: { shushu: 2, benzhigaoshou: 1, laoban: 2, shoucangjia: 1 },
      },
      {
        id: "100m-200m",
        label: "100M - 200M",
        description: "你对资源管理和收益效率都比较有掌控。",
        dimensionDeltas: { loot: 2, rational: 2, tactics: 2 },
        meaningDeltas: { efficiency: 3, profit: 1, control: 1 },
        personaSignals: { laoban: 3, shoucangjia: 2, benzhigaoshou: 2, hadesen: 2 },
      },
      {
        id: "over-200m",
        label: "200M+",
        description: "长期积累能力强，偏囤积和长期运营。",
        dimensionDeltas: { loot: 2, rational: 1, tactics: 1 },
        meaningDeltas: { collection: 3, profit: 2 },
        personaSignals: { shoucangjia: 3, laoban: 2, shushu: 2 },
      },
    ],
  },
  {
    id: "fun-source",
    prompt: "对你来说，三角洲行动最好玩的是？",
    brief: "这题直接测你的爽点来源，是结果区分度最高的一题之一。",
    options: [
      {
        id: "easy-loot",
        label: "休闲摸金，把东西带出去就行，偶尔出红会很开心",
        description: "舒服撤离本身就是一种奖励。",
        dimensionDeltas: { loot: 2, combat: -1, rational: 1, tactics: 1 },
        meaningDeltas: { profit: 3 },
        personaSignals: { shushu: 2, laoban: 2 },
        easterEggSignals: { tangwang: 0.5 },
      },
      {
        id: "conquer-headon",
        label: "正面狠狠干赢一波，主打一个征服，自己打的包才好吃",
        description: "狠狠干不只是赢法，还是情绪出口。",
        dimensionDeltas: { combat: 3, emotion: 2, team: 1, loot: -1 },
        meaningDeltas: { kill: 3, destruction: 1 },
        personaSignals: { menggonglang: 2, weilong: 2, saiyide: 2, leisi: 1 },
      },
      {
        id: "read-the-game",
        label: "靠意识、战术、随机应变赢得每场胜利",
        description: "把局势玩明白，比乱杀更爽。",
        dimensionDeltas: { tactics: 3, rational: 3, combat: 1, team: 1 },
        meaningDeltas: { control: 3 },
        personaSignals: { benzhigaoshou: 2, hadesen: 2, jiaoguan: 1 },
      },
      {
        id: "friends-extract",
        label: "和好友一起玩，一起撤才有成就感",
        description: "你最在乎的是人和结果都在。",
        dimensionDeltas: { team: 3, rational: 1, combat: -1, loot: -1 },
        meaningDeltas: { care: 2, guardianship: 1 },
        personaSignals: { mama: 2, jiaoguan: 2, demulan: 2, weilong: 1 },
      },
      {
        id: "fill-collection",
        label: "让大红填满收藏室吧",
        description: "带出去很爽，但塞进收藏室更爽。",
        dimensionDeltas: { loot: 2, rational: 1, combat: -1, tactics: 1 },
        meaningDeltas: { collection: 4 },
        personaSignals: { shoucangjia: 4, shushu: 1 },
        easterEggSignals: { tangwang: 0.5 },
      },
      {
        id: "tilt-people",
        label: "扰民、无人机、喜欢听对面喊我的假牙",
        description: "打赢不是唯一快乐，让人难受才是真乐子。",
        dimensionDeltas: { emotion: 2, tactics: 1, combat: 1, team: -1 },
        meaningDeltas: { torment: 4, disruption: 1 },
        personaSignals: { duya: 1, leisi: 0.5 },
        easterEggSignals: { laobeizha: 2 },
      },
      {
        id: "camp-and-tax",
        label: "堵桥来",
        description: "空间本身也可以变成武器。",
        dimensionDeltas: { tactics: 2, rational: 1, combat: 1, team: -1, loot: 1 },
        meaningDeltas: { taxation: 4, torment: 1 },
        personaSignals: { tujiu: 0.5 },
        easterEggSignals: { duqiaolai: 2, laobeizha: 1 },
      },
    ],
  },
  {
    id: "core-zone-quiet",
    prompt: "如果你进入核心区前，没有听到一点动静，你会怎么做？",
    brief: "同样是“安静”，有人会读局，有人会避险，有人会主动点火。",
    options: [
      {
        id: "cheap-and-earn",
        label: "反正卡战备进的，吃多少赚多少",
        description: "低成本进场，默认白赚心态。",
        dimensionDeltas: { loot: 2, rational: 1, tactics: -1, combat: -1 },
        meaningDeltas: { profit: 2, fate: 1 },
        personaSignals: { shushu: 2, laoban: 2 },
      },
      {
        id: "collect-info",
        label: "收集信息，稳健推进，保持警惕",
        description: "安静不代表空白，可能只是信息还没被读出来。",
        dimensionDeltas: { tactics: 3, rational: 2, combat: 1, team: 1 },
        meaningDeltas: { control: 2, efficiency: 1 },
        personaSignals: { benzhigaoshou: 2, jiaoguan: 2, hadesen: 2, demulan: 1 },
      },
      {
        id: "occupy-and-fight",
        label: "占领要地，见人就干",
        description: "先把气势和空间拿住，碰人就打。",
        dimensionDeltas: { combat: 3, emotion: 2, tactics: 1, loot: -1 },
        meaningDeltas: { kill: 3, destruction: 1 },
        personaSignals: { menggonglang: 2, weilong: 2, saiyide: 2, leisi: 1 },
      },
      {
        id: "detour",
        label: "越安静的地方越危险，绕路而行",
        description: "你默认有坑，先规避再说。",
        dimensionDeltas: { tactics: 2, rational: 2, combat: -2, loot: 1 },
        meaningDeltas: { efficiency: 1, profit: 1 },
        personaSignals: { shushu: 2, tujiu: 1, laoban: 2, shoucangjia: 1 },
      },
      {
        id: "magnet-bomb",
        label: "磁吸炸弹投出！",
        description: "没动静就制造动静，把局面点起来。",
        dimensionDeltas: { emotion: 2, tactics: 1, combat: 1, team: -1 },
        meaningDeltas: { torment: 3, disruption: 2, taxation: 1 },
        personaSignals: { duya: 2, leisi: 0.5 },
        easterEggSignals: { laobeizha: 2 },
      },
    ],
  },
  {
    id: "teammate-downed",
    prompt: "队友在前点被放倒了，位置不算好，周围还可能有敌人架着。你会怎么做？",
    brief: "核心骨干题：测你在高压救援场景下的责任、理性和推进方式。",
    options: [
      {
        id: "method-rescue",
        label: "正常打，能拉就拉，但不能白给第二个",
        description: "不是不救，是按局势救。",
        dimensionDeltas: { team: 2, tactics: 2, rational: 2, combat: 1 },
        meaningDeltas: { care: 1, guardianship: 1, control: 1 },
        personaSignals: { jiaoguan: 2, benzhigaoshou: 2, mama: 2, demulan: 1 },
      },
      {
        id: "wipe-then-rescue",
        label: "先打赢再考虑救人，我这就去狠狠干对面",
        description: "先把让队友倒地的原因狠狠干掉。",
        dimensionDeltas: { combat: 3, emotion: 2, team: 1 },
        meaningDeltas: { kill: 2, belief: 1 },
        personaSignals: { menggonglang: 2, saiyide: 2, weilong: 2, leisi: 1 },
      },
      {
        id: "rescue-first",
        label: "封烟也好，背人也好，先把人救起来优先",
        description: "不先问值不值，先问人能不能起来。",
        dimensionDeltas: { team: 4, emotion: 1, tactics: 1 },
        meaningDeltas: { care: 2, guardianship: 2 },
        personaSignals: { mama: 3, weilong: 2, demulan: 2, saiyide: 1 },
      },
      {
        id: "cover-and-rescue",
        label: "我来架枪，队友来救",
        description: "这波不是谁热血，是谁干自己的活。",
        dimensionDeltas: { team: 3, tactics: 3, rational: 2, combat: 1 },
        meaningDeltas: { command: 2, control: 2 },
        personaSignals: { jiaoguan: 2, demulan: 2, hadesen: 2, benzhigaoshou: 2 },
      },
      {
        id: "cut-losses",
        label: "这波没法救了，再送就是全没，先止损",
        description: "承认这波已经烂了，先保全大局。",
        dimensionDeltas: { rational: 3, tactics: 2, team: -2, combat: -1 },
        meaningDeltas: { efficiency: 3, control: 1 },
        personaSignals: { hadesen: 2, laoban: 2, shushu: 2, demulan: 1 },
      },
    ],
  },
  {
    id: "full-gear-shattered",
    prompt: "如果你这把起了一套全装，结果刚进图就被炸碎甲了，你会怎么想？",
    brief: "这题直接测你被打断节奏后的第一反应。",
    options: [
      {
        id: "revenge-now",
        label: "我的假牙！对面你完蛋了",
        description: "先复仇，先狠狠干，把气出了再说。",
        dimensionDeltas: { emotion: 3, combat: 2, tactics: -1, team: -1 },
        meaningDeltas: { kill: 2, destruction: 2, belief: 1 },
        personaSignals: { menggonglang: 2, saiyide: 2, leisi: 2 },
      },
      {
        id: "fallback-first",
        label: "起码没死，撤退一下暂避锋芒，活下来最重要",
        description: "止损优先，不跟这口气硬刚。",
        dimensionDeltas: { rational: 2, combat: -2, tactics: 2, loot: 1 },
        meaningDeltas: { efficiency: 2, profit: 1 },
        personaSignals: { shushu: 2, laoban: 2, shoucangjia: 1 },
      },
      {
        id: "recover-and-counter",
        label: "打状态，并随时准备反击",
        description: "先稳住，再找窗口把节奏拿回来。",
        dimensionDeltas: { tactics: 3, rational: 2, combat: 1, team: 1 },
        meaningDeltas: { control: 2, efficiency: 1 },
        personaSignals: { benzhigaoshou: 2, weilong: 1, jiaoguan: 1, hadesen: 1 },
      },
      {
        id: "join-the-chaos",
        label: "自己老贝榨？打不过就加入",
        description: "既然被恶心了，那我也来当恶心人的那个。",
        dimensionDeltas: { emotion: 2, tactics: 1, combat: 1, team: -1 },
        meaningDeltas: { torment: 4, disruption: 1 },
        personaSignals: { duya: 1, leisi: 0.5 },
        easterEggSignals: { laobeizha: 2 },
      },
      {
        id: "no-armor",
        label: "长官，我身上没有甲",
        description: "先想怎么把收益和命保住。",
        dimensionDeltas: { loot: 3, combat: -1 },
        meaningDeltas: { profit: 2, fate: 2 },
        personaSignals: { shushu: 2, shoucangjia: 1, laoban: 1 },
        easterEggSignals: { tangwang: 1 },
      },
    ],
  },
  {
    id: "red-loot-footsteps",
    prompt: "你在房区里摸到一个大红，这时候外面突然传来一串脚步，你第一反应更像？",
    brief: "这题测你在“高价值资源 + 即时威胁”下的默认打法。",
    options: [
      {
        id: "freeze-hide",
        label: "一二三木头人，找好角落趴下玩手机",
        description: "先把货保住，先活着。",
        dimensionDeltas: { loot: 2, combat: -3, tactics: 1, rational: 1 },
        meaningDeltas: { profit: 2, collection: 1 },
        personaSignals: { shushu: 2, shoucangjia: 2, laoban: 1 },
        // TODO: 原稿有“夺舍的狼 +1”，该彩蛋尚未定义，暂不接入。
      },
      {
        id: "pick-and-disrupt",
        label: "先找角度偷一个，能打乱他们最好",
        description: "不一定硬接，但先把对面节奏拆掉。",
        dimensionDeltas: { tactics: 3, combat: 1, rational: 1, loot: -1 },
        meaningDeltas: { disruption: 2, control: 1 },
        personaSignals: { benzhigaoshou: 2, duya: 2, tujiu: 1 },
      },
      {
        id: "call-support",
        label: "请求队友支援，在此之前保持存活",
        description: "先稳住自己，再把团队资源调过来。",
        dimensionDeltas: { team: 3, tactics: 2, rational: 2, combat: -1 },
        meaningDeltas: { care: 2, guardianship: 1 },
        personaSignals: { mama: 2, jiaoguan: 2, demulan: 2, weilong: 1 },
      },
      {
        id: "route-out",
        label: "先规划撤离路线，必须把货带走",
        description: "你会第一时间在脑里画撤离图。",
        dimensionDeltas: { loot: 3, rational: 2, tactics: 2, combat: -2 },
        meaningDeltas: { profit: 3, efficiency: 1 },
        personaSignals: { shushu: 2, laoban: 2, shoucangjia: 2, hadesen: 1 },
      },
      {
        id: "keep-looting",
        label: "感觉这把爆率不错，接着摸",
        description: "你对命格和连红有一种强信心。",
        dimensionDeltas: { loot: 3, rational: -1, emotion: 1, combat: -1 },
        meaningDeltas: { fate: 3, profit: 2 },
        personaSignals: { shoucangjia: 1, tujiu: 1 },
        easterEggSignals: { tangwang: 2 },
      },
    ],
  },
  {
    id: "last-gate-ambush",
    prompt: "这已经是最后一个闸，发现撤离点已经有人提前埋伏，你更倾向于？",
    brief: "最后关头更能看出你是止损派、控场派还是硬刚派。",
    options: [
      {
        id: "drop-and-detour",
        label: "丢包避开这个闸，没必要硬碰硬",
        description: "先保命，不为一口气赌全局。",
        dimensionDeltas: { rational: 2, tactics: 2, combat: -3, loot: -1 },
        meaningDeltas: { efficiency: 2, profit: 1 },
        personaSignals: { shushu: 2, laoban: 2, shoucangjia: 1 },
      },
      {
        id: "info-then-go",
        label: "收集对方位置信息，看情况打，不行就丢包混烟撤",
        description: "你会先读局，再决定打或走。",
        dimensionDeltas: { tactics: 3, rational: 3, combat: 1, team: 1 },
        meaningDeltas: { control: 3, efficiency: 1 },
        personaSignals: { benzhigaoshou: 2, jiaoguan: 2, hadesen: 2, demulan: 1 },
      },
      {
        id: "fight-for-face",
        label: "敢跟我抢撤离？直接猛猛干",
        description: "这不只是撤离问题，更是面子问题。",
        dimensionDeltas: { combat: 3, emotion: 3, tactics: -1, team: -1 },
        meaningDeltas: { kill: 3, destruction: 1 },
        personaSignals: { menggonglang: 2, saiyide: 2, leisi: 2, weilong: 1 },
      },
      {
        id: "vanguard-extract",
        label: "我来当先锋闯出这条生路，大家必须一起撤出去",
        description: "你会主动扛风险，换团队完整撤离。",
        dimensionDeltas: { team: 3, combat: 2, tactics: 1, emotion: 1 },
        meaningDeltas: { guardianship: 2, command: 2, care: 1 },
        personaSignals: { weilong: 2, jiaoguan: 2, mama: 1, demulan: 1 },
      },
      {
        id: "i-am-ambush",
        label: "我就是那个提前埋伏的",
        description: "你把撤离点当作空间武器来用。",
        dimensionDeltas: { tactics: 2, rational: 1, combat: 1, team: -1, loot: 1 },
        meaningDeltas: { taxation: 4, torment: 1, disruption: 1 },
        personaSignals: { duya: 1, tujiu: 0.5 },
        easterEggSignals: { duqiaolai: 2, laobeizha: 1 },
      },
    ],
  },
  {
    id: "team-split",
    prompt: "这把进图后，队友各奔东西，有人想打，有人想摸，你更像会怎么做的人？",
    brief: "这题看你面对团队失序时，是控场、跟随、切割还是单干。",
    options: [
      {
        id: "try-comm-then-self-save",
        label: "试图开麦沟通，如果无效就自己猥琐点保证撤离",
        description: "先救队伍，救不了就保自己。",
        dimensionDeltas: { team: 2, rational: 2, tactics: 2, combat: -1 },
        meaningDeltas: { command: 1, care: 1, efficiency: 1, profit: 1 },
        personaSignals: { jiaoguan: 2, mama: 1, shushu: 1, demulan: 1 },
      },
      {
        id: "follow-me",
        label: "告诉队友，跟我走，这把包得吃",
        description: "你会尝试把分裂局面重新并轨。",
        dimensionDeltas: { team: 2, combat: 1, emotion: 1, tactics: 1 },
        meaningDeltas: { command: 2, guardianship: 1, profit: 1 },
        personaSignals: { jiaoguan: 2, weilong: 2, saiyide: 1, demulan: 1 },
      },
      {
        id: "just-loot",
        label: "事已至此，我也开吃吧",
        description: "局都散了，那就先把收益拿稳。",
        dimensionDeltas: { loot: 3, team: -2, rational: 1, combat: -1 },
        meaningDeltas: { profit: 3, collection: 1 },
        personaSignals: { shushu: 2, tujiu: 2, laoban: 2, shoucangjia: 1 },
        easterEggSignals: { tangwang: 1 },
      },
      {
        id: "follow-one",
        label: "跟着其中一个队友",
        description: "你会把决策权临时外包给离你最近的人。",
        dimensionDeltas: { team: 1, rational: 1, tactics: -1 },
        meaningDeltas: { efficiency: 1 },
        personaSignals: { laoban: 1, mama: 1, shushu: 1 },
      },
      {
        id: "solo-rush",
        label: "直接开始单三猛攻教学",
        description: "你不想拉队伍，只想把场面打穿。",
        dimensionDeltas: { combat: 3, emotion: 3, team: -2, tactics: -1 },
        meaningDeltas: { kill: 3, destruction: 1 },
        personaSignals: { menggonglang: 2, leisi: 2, saiyide: 1, weilong: 0.5 },
      },
    ],
  },
  {
    id: "hate-point",
    prompt: "你在局里最讨厌哪一种情况？",
    brief: "很多时候，一个人最讨厌什么，比最喜欢什么更诚实。",
    options: [
      {
        id: "no-extract-after-wins",
        label: "打赢了很多队却没撤出去",
        description: "不是不能打，是不能白打。",
        dimensionDeltas: { combat: 2, rational: 1, loot: 2, tactics: 1 },
        meaningDeltas: { profit: 2, kill: 1 },
        personaSignals: { weilong: 2, menggonglang: 2, benzhigaoshou: 2, shushu: 1 },
      },
      {
        id: "bad-comms",
        label: "没人交流，配合特别差而导致撤离失败",
        description: "最恶心的不是输，是一队人各打各的。",
        dimensionDeltas: { team: 4, rational: 2, tactics: 2, combat: -1 },
        meaningDeltas: { command: 2, care: 1 },
        personaSignals: { jiaoguan: 2, mama: 2, demulan: 2, weilong: 1 },
      },
      {
        id: "my-own-mistake",
        label: "自己没发挥好，对局势有误判，操作有失误",
        description: "怪自己比怪别人更让你难受。",
        dimensionDeltas: { tactics: 4, rational: 3, combat: 1, team: 1 },
        meaningDeltas: { control: 4, efficiency: 1 },
        personaSignals: { benzhigaoshou: 2, hadesen: 2, jiaoguan: 2, weilong: 1 },
      },
      {
        id: "dirty-enemy",
        label: "对面不跟你正面交火，只会恶心人",
        description: "你讨厌输得不痛快，更讨厌被脏套路磨。",
        dimensionDeltas: { combat: 2, emotion: 2, tactics: -1 },
        meaningDeltas: { kill: 2, destruction: 1 },
        personaSignals: { menggonglang: 2, weilong: 2, leisi: 2, saiyide: 1 },
        easterEggSignals: { laobeizha: 1, duqiaolai: 1 },
      },
      {
        id: "low-drop-rate",
        label: "爆率太低，摸不到大红",
        description: "你可以不狠狠干，但不能不出红。",
        dimensionDeltas: { loot: 4, rational: 1, combat: -1 },
        meaningDeltas: { profit: 4, collection: 1, fate: 1 },
        personaSignals: { shushu: 2, shoucangjia: 3, laoban: 2 },
        easterEggSignals: { tangwang: 1 },
      },
    ],
  },
  {
    id: "lead-call",
    prompt: "如果这把两个野排队友说都听你的，你大概率会做什么决定？",
    brief: "这题最能测你到底会带队、开路、托底，还是直接收税。",
    options: [
      {
        id: "normal-command",
        label: "正常打，我来指挥行动",
        description: "带队不是热血，是把节奏和撤退一起管住。",
        dimensionDeltas: { team: 4, tactics: 3, rational: 3, combat: 1 },
        meaningDeltas: { command: 4, control: 1 },
        personaSignals: { jiaoguan: 2, demulan: 2, benzhigaoshou: 2, hadesen: 1 },
      },
      {
        id: "lead-rush",
        label: "带队猛攻，做冲在前面的人",
        description: "你更像行动派领头羊，不像秩序派队长。",
        dimensionDeltas: { combat: 4, team: 2, emotion: 2, tactics: 1 },
        meaningDeltas: { kill: 3, guardianship: 1 },
        personaSignals: { weilong: 2, menggonglang: 2, saiyide: 2, leisi: 1 },
      },
      {
        id: "last-line",
        label: "告诉队友放心打，你来兜底，谁倒了拉谁",
        description: "你想当最后防线，而不是第一发枪响。",
        dimensionDeltas: { team: 4, tactics: 2, rational: 1, combat: -1 },
        meaningDeltas: { care: 4, guardianship: 1 },
        personaSignals: { mama: 2, jiaoguan: 2, demulan: 2, weilong: 1 },
      },
      {
        id: "rat-refusal",
        label: "兄弟，我是跑刀的",
        description: "这把想带队的是你，不是我，我先保本。",
        dimensionDeltas: { loot: 3, team: -2, rational: 1, combat: -2 },
        meaningDeltas: { profit: 3 },
        personaSignals: { shushu: 2, laoban: 2, shoucangjia: 1 },
        easterEggSignals: { tangwang: 1 },
      },
      {
        id: "tax-route",
        label: "堵桥来",
        description: "你不是要带人狠狠干，你是要带人去控空间。",
        dimensionDeltas: { tactics: 2, rational: 1, combat: 1, team: -1, loot: 1 },
        meaningDeltas: { taxation: 4, torment: 1 },
        personaSignals: { duya: 1 },
        easterEggSignals: { duqiaolai: 2, laobeizha: 1 },
      },
    ],
  },
  {
    id: "rich-but-greedy",
    prompt: "如果你这把已经很肥了，队友却还想继续贪，你通常会？",
    brief: "这题主要看你是止盈派、陪跑派，还是继续冲收益派。",
    options: [
      {
        id: "call-extract",
        label: "通知队友快撤，再贪一无所有",
        description: "你更在乎把已经拿到的结果稳定兑现。",
        dimensionDeltas: { rational: 3, team: 2, loot: -1, combat: -1 },
        meaningDeltas: { efficiency: 3, command: 1 },
        personaSignals: { jiaoguan: 2, hadesen: 2, demulan: 2, shushu: 1 },
      },
      {
        id: "keep-fighting",
        label: "贪呗，来人我接着干",
        description: "肥了就打，风险和收益一起上。",
        dimensionDeltas: { combat: 3, emotion: 2, team: 1, loot: 1 },
        meaningDeltas: { kill: 2, guardianship: 1 },
        personaSignals: { menggonglang: 2, weilong: 2, saiyide: 2, leisi: 1 },
      },
      {
        id: "cover-for-team",
        label: "找个好地方帮他们侦查放风",
        description: "你不一定认同继续贪，但会尽力给团队托底。",
        dimensionDeltas: { team: 3, tactics: 3, rational: 2 },
        meaningDeltas: { care: 1, command: 2, guardianship: 1, control: 1 },
        personaSignals: { mama: 2, jiaoguan: 2, benzhigaoshou: 1, demulan: 1 },
      },
      {
        id: "fly-rat",
        label: "我已飞鼠",
        description: "你会先把当天战果落袋为安。",
        dimensionDeltas: { loot: 2, team: -2, rational: 2, combat: -2 },
        meaningDeltas: { profit: 3, efficiency: 1 },
        personaSignals: { shushu: 2, laoban: 2, shoucangjia: 1 },
        easterEggSignals: { tangwang: 1 },
      },
      {
        id: "more-money",
        label: "还有小金吗？赚钱怎么能叫贪呢",
        description: "你的上头方向不是打架，是继续赚。",
        dimensionDeltas: { loot: 4, emotion: 1, rational: -1 },
        meaningDeltas: { profit: 4, collection: 1, fate: 1 },
        personaSignals: { shoucangjia: 2, tujiu: 2, laoban: 1 },
        easterEggSignals: { tangwang: 1 },
      },
    ],
  },
  {
    id: "fixed-team",
    prompt: "找固排，你会选择？",
    brief: "这题看你理想队伍结构：秩序、猛攻、收益或玩法共谋。",
    options: [
      {
        id: "reliable-team",
        label: "可靠的，懂配合的",
        description: "你更看重稳定协作和长期默契。",
        dimensionDeltas: { team: 4, tactics: 2, rational: 2, combat: 1 },
        meaningDeltas: { command: 3, care: 1, guardianship: 1 },
        personaSignals: { jiaoguan: 2, mama: 2, demulan: 2, benzhigaoshou: 1 },
      },
      {
        id: "rush-brothers",
        label: "能一起猛攻的兄弟",
        description: "你希望队友能跟你同频狠狠干。",
        dimensionDeltas: { combat: 4, emotion: 2, team: 1 },
        meaningDeltas: { kill: 3, guardianship: 1 },
        personaSignals: { menggonglang: 2, weilong: 2, saiyide: 2, leisi: 1 },
      },
      {
        id: "loot-rats",
        label: "一起跑刀的鼠鼠",
        description: "你追求的是稳定保本和一起发财。",
        dimensionDeltas: { loot: 4, team: 1, rational: 2, combat: -2 },
        meaningDeltas: { profit: 4, collection: 1 },
        personaSignals: { shushu: 3, laoban: 2, shoucangjia: 1 },
      },
      {
        id: "pay-for-carry",
        label: "使用钞能力找航天双子星",
        description: "你愿意用资源换效率和结果。",
        dimensionDeltas: { loot: 2, team: -1, rational: 2 },
        meaningDeltas: { efficiency: 3, profit: 1 },
        personaSignals: { laoban: 2, shushu: 1 },
        // TODO: 原稿“航天双子星 +2”为未定义彩蛋，暂不接入。
      },
      {
        id: "tax-squad",
        label: "堵桥来",
        description: "你想要的是玩法同盟，不只是队友。",
        dimensionDeltas: { tactics: 2, rational: 1, combat: 1, team: -1, loot: 1 },
        meaningDeltas: { taxation: 4, torment: 1, disruption: 1 },
        personaSignals: { duya: 1, tujiu: 1 },
        easterEggSignals: { duqiaolai: 2 },
      },
    ],
  },
  {
    id: "friendly-rat",
    prompt: "如果你遇到一队友好鼠鼠，你会怎么做？",
    brief: "这题测的是你对陌生善意的处理方式：合作、切割、利用或清除。",
    options: [
      {
        id: "peace-extract",
        label: "摇头晃脑，互相给小金，一起撤离",
        description: "你愿意把临时关系变成互利共识。",
        dimensionDeltas: { team: 3, rational: 1, loot: 2, combat: -1 },
        meaningDeltas: { care: 2, profit: 2, guardianship: 1 },
        personaSignals: { mama: 2, shushu: 2, shoucangjia: 1, laoban: 1 },
      },
      {
        id: "shoot-first",
        label: "我信不过别人，不确定同盟关系，直接开枪",
        description: "你更接受消灭不确定，而不是冒合作风险。",
        dimensionDeltas: { combat: 2, rational: 1, team: -2 },
        meaningDeltas: { kill: 2, efficiency: 1, control: 1 },
        personaSignals: { weilong: 2, menggonglang: 2, hadesen: 1, leisi: 1 },
      },
      {
        id: "betray-at-extract",
        label: "等会到撤离点背刺",
        description: "你会把“友好关系”也纳入局势操作。",
        dimensionDeltas: { tactics: 2, emotion: 1, team: -3, loot: 1, combat: 1 },
        meaningDeltas: { disruption: 3, torment: 1, profit: 1 },
        personaSignals: { duya: 3, tujiu: 1, leisi: 0.5 },
      },
      {
        id: "escort-rat",
        label: "保护鼠鼠，一路过关斩将",
        description: "你愿意主动扛风险，护送别人安全撤离。",
        dimensionDeltas: { team: 4, combat: 2, emotion: 1, loot: 1 },
        meaningDeltas: { guardianship: 3, care: 2, belief: 1 },
        personaSignals: { weilong: 2, mama: 2, saiyide: 2, jiaoguan: 1 },
      },
      {
        id: "walk-away",
        label: "径直离开，各自吃各自的",
        description: "你承认彼此存在，但不建立关系。",
        dimensionDeltas: { rational: 2, tactics: 1, team: -1, loot: 2, combat: -1 },
        meaningDeltas: { efficiency: 1, profit: 2, collection: 1 },
        personaSignals: { shushu: 2, shoucangjia: 1, laoban: 2, benzhigaoshou: 1 },
      },
    ],
  },
  {
    id: "loot-attitude",
    prompt: "你对摸金的态度是？",
    brief: "核心骨干题：区分收益偏好、门槛接受度和战斗取向。",
    options: [
      {
        id: "small-to-big",
        label: "那肯定得是小金起步，摸到大红更好。",
        description: "你对收益有清晰期待，且期待会持续升级。",
        dimensionDeltas: { loot: 4, rational: 1, combat: -1, tactics: 1 },
        meaningDeltas: { profit: 3, collection: 3, efficiency: 1 },
        personaSignals: { shoucangjia: 2, shushu: 2, laoban: 1 },
      },
      {
        id: "small-is-enough",
        label: "摸到小蓝小紫就很开心了。",
        description: "核心是先有正反馈、先有进账，门槛低但很稳定。",
        dimensionDeltas: { loot: 2, rational: 2, combat: -1, tactics: 1 },
        meaningDeltas: { profit: 3, efficiency: 2, fate: 1 },
        personaSignals: { shushu: 2, laoban: 1, shoucangjia: 1 },
        easterEggSignals: { xipubawang: 2 },
      },
      {
        id: "enemy-bag-best",
        label: "盒子里的装备更好吃。",
        description: "地图给的不如狠狠干出来的，你更偏强打获取。",
        dimensionDeltas: { combat: 3, emotion: 1, loot: 1, tactics: 1 },
        meaningDeltas: { kill: 3, destruction: 1 },
        personaSignals: { menggonglang: 2, benzhigaoshou: 1, weilong: 1, saiyide: 1 },
      },
      {
        id: "eat-anything",
        label: "有啥吃啥，不挑。",
        description: "别空手就行，来什么都算今天有收获。",
        dimensionDeltas: { loot: 3, rational: 1, combat: -1 },
        meaningDeltas: { profit: 3, fate: 1 },
        personaSignals: { shushu: 2, laoban: 1, shoucangjia: 1 },
        easterEggSignals: { tangwang: 1 },
      },
      {
        id: "rich-by-default",
        label: "钞能力不需要吃饭。",
        description: "你不是靠摸金维生，资源安全感本身就很高。",
        dimensionDeltas: { loot: -1, rational: 1, team: -1 },
        meaningDeltas: { efficiency: 3, style: 1 },
        personaSignals: { laoban: 2, menggonglang: 0.5 },
      },
    ],
  },
  {
    id: "weapon",
    prompt: "你最常用的枪械是？",
    brief: "这题主要抓你的价值观，不是单纯抓枪型。",
    options: [
      {
        id: "cheap-practical",
        label: "便宜好用的粑粑枪",
        description: "能打、够省、够稳，比牌面更重要。",
        dimensionDeltas: { rational: 2, loot: 1, tactics: 1 },
        meaningDeltas: { efficiency: 2, profit: 1 },
        personaSignals: { shushu: 2, laoban: 2, benzhigaoshou: 1 },
      },
      {
        id: "meta-guns",
        label: "天王系列 M7、MK47、Asval",
        description: "强枪就是强枪，狠狠干赢了再说。",
        dimensionDeltas: { combat: 2, emotion: 1, tactics: 1, loot: -1 },
        meaningDeltas: { kill: 3 },
        personaSignals: { menggonglang: 2, weilong: 2, benzhigaoshou: 2, saiyide: 1 },
      },
      {
        id: "value-build",
        label: "性价比，有强度还不贵的",
        description: "我可以不花冤枉钱，但输出不能差。",
        dimensionDeltas: { rational: 3, tactics: 2, loot: 1, combat: 1 },
        meaningDeltas: { efficiency: 4, control: 1 },
        personaSignals: { benzhigaoshou: 2, laoban: 2, hadesen: 2, shushu: 1 },
      },
      {
        id: "my-own-build",
        label: "自己研发的就行",
        description: "枪不一定最主流，但得有我的理解。",
        dimensionDeltas: { tactics: 2, rational: 1, combat: 1, loot: -1 },
        meaningDeltas: { style: 4, control: 1 },
        personaSignals: { benzhigaoshou: 1, duya: 1 },
        easterEggSignals: { jiahao: 2 },
      },
      {
        id: "picked-up",
        label: "小兵身上的",
        description: "现捡现用，命格在线就够了。",
        dimensionDeltas: { loot: 2, rational: 1, tactics: -1 },
        meaningDeltas: { fate: 3, profit: 1 },
        personaSignals: { shushu: 2, laoban: 1 },
        easterEggSignals: { tangwang: 2 },
      },
    ],
  },
];

export const questionsById = Object.fromEntries(
  questionBank.map((question) => [question.id, question]),
) as Record<Question["id"], Question>;

const questionFlowOrder: QuestionId[] = [
  // Part A: 开场破冰（锁尾：asset-level）
  "backpack",
  "operator",
  "map",
  "difficulty",
  "asset-level",
  // Part B: 中段混合（骨干/T2打散，锁尾：loot-attitude）
  "gunfire",
  "core-zone-quiet",
  "teammate-downed",
  "after-fight",
  "full-gear-shattered",
  "single-extract-priority",
  "red-loot-footsteps",
  "weapon",
  "last-gate-ambush",
  "loadout",
  "team-split",
  "hate-point",
  "lead-call",
  "rich-but-greedy",
  "fixed-team",
  "friendly-rat",
  "loot-attitude",
  // Part C: 收尾固定题（锁尾：fun-source / Q10）
  "fun-source",
];

export const questions: Question[] = questionFlowOrder.map((questionId) => questionsById[questionId]);
